(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],D=window.APP_DATA||{subjects:[],lessons:[],questions:[],tests:[],materials:[]};
const state={user:null,route:location.hash.slice(1)||"home",theme:localStorage.getItem("bt_theme")||"light",results:JSON.parse(localStorage.getItem("bt_results")||"[]"),favorites:JSON.parse(localStorage.getItem("bt_favs")||"[]"),quiz:null};
document.documentElement.dataset.theme=state.theme;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const subj=id=>D.subjects.find(x=>x.id===id)||{id,name:id,icon:"📘",color:"blue"};
function toast(t){const e=$("#toast");if(!e)return;e.textContent=t;e.classList.add("show");clearTimeout(window._tt);window._tt=setTimeout(()=>e.classList.remove("show"),2200)}
function saveLocal(){localStorage.setItem("bt_results",JSON.stringify(state.results));localStorage.setItem("bt_favs",JSON.stringify(state.favorites))}
function nav(r){state.route=r;location.hash=r;render();$("#sidebar")?.classList.remove("open");scrollTo({top:0,behavior:"smooth"})}
function metric(i,n,l){return `<div class="metric"><span>${i}</span><div><b>${n}</b><small>${l}</small></div></div>`}
async function restore(){if(!API.token)return;try{const j=await API.get("/api/me");state.user=j.user}catch{API.setToken("")}}
function shell(){const u=state.user;$("#sideName").textContent=u?.name||"Khách";$("#sideRole").textContent=u?({student:"Học sinh",parent:"Phụ huynh",teacher:"Giáo viên",admin:"Quản trị viên"}[u.role]||u.role):"Học sinh";$("#sideAvatar").textContent=u?.avatar||"👧🏻";$("#authBtn").textContent=u?"Đăng xuất":"Đăng nhập";$$(".admin-only").forEach(x=>x.style.display=u?.role==="admin"?"flex":"none");$$(".teacher-only").forEach(x=>x.style.display=["teacher","admin"].includes(u?.role)?"flex":"none")}
function pageHead(k,t,p=""){return `<section class="page-head"><span class="eyebrow">${k}</span><h1>${t}</h1><p>${p}</p></section>`}
function hero(){return `<section class="hero"><div class="hero-copy"><span class="pill">✨ HỌC VUI MỖI NGÀY</span><h1>Bài Tập <em>Cấp 1</em></h1><h2>Học vui – Luyện giỏi – Tiến bộ mỗi ngày</h2><p>Học theo lớp, làm bài, xem tiến bộ, tham gia lớp của giáo viên và nhận gợi ý học tập cá nhân.</p><div class="hero-search"><input id="globalSearch" placeholder="Tìm bài học, môn học, tài liệu..."><button id="globalSearchBtn">Tìm kiếm</button></div><div class="quick-grades">${[1,2,3,4,5].map(g=>`<button data-grade="${g}">Lớp ${g}</button>`).join("")}</div></div><div class="hero-art"><div class="bubble">⭐ Học mỗi ngày</div><div class="big-kid">👧🏻📚</div><div class="bubble second">🏆 Tiến bộ</div></div></section>`}
function lessonRow(l){const s=subj(l.subject),fav=state.favorites.includes(l.id);return `<div class="lesson-row"><div class="lesson-ico">${s.icon}</div><div class="grow"><b>${esc(l.title)}</b><small>${s.name} • Lớp ${l.grade} • ${l.topic||""} • ${l.level||""}</small></div><button class="heart" data-fav="${l.id}">${fav?"❤️":"🤍"}</button><button class="outline small" data-start="${l.subject}" data-grade="${l.grade}">Luyện tập</button></div>`}
function home(){const avg=state.results.length?Math.round(state.results.reduce((a,b)=>a+b.score,0)/state.results.length):0;return hero()+`<section class="metrics">${metric("📝",state.results.length,"Bài đã làm")}${metric("🎯",avg+"%","Điểm trung bình")}${metric("❤️",state.favorites.length,"Bài đã lưu")}${metric("🔥","3","Ngày liên tiếp")}</section><section class="section"><div class="section-head"><div><span class="eyebrow">KHÁM PHÁ</span><h2>Môn học nổi bật</h2></div></div><div class="subject-grid">${D.subjects.map(s=>`<article class="subject-card ${s.color}"><div class="subject-icon">${s.icon}</div><h3>${s.name}</h3><p>${s.desc||""}</p><button class="primary small" data-subject="${s.id}">Xem bài tập →</button></article>`).join("")}</div></section><section class="section split"><div><div class="section-head"><h2>⭐ Bài tập mới</h2></div><div class="list-card">${D.lessons.slice(0,6).map(lessonRow).join("")}</div></div><div class="panel"><h3>⚡ Truy cập nhanh</h3><div class="admin-actions"><button class="outline" data-route="classes">🏫 Lớp học</button><button class="outline" data-route="assignments">📌 Bài được giao</button><button class="outline" data-route="analytics">📊 Phân tích</button><button class="outline" data-route="notifications">🔔 Thông báo</button><button class="outline" data-route="submissions">📨 Chấm bài</button></div></div></section>`}
function subjects(){return pageHead("THƯ VIỆN","Môn học & bài tập","Tìm không dấu, lọc theo lớp/môn/mức độ.")+`<section class="filterbar"><input id="lessonSearch" placeholder="🔎 Tìm bài..."><select id="gradeFilter"><option value="">Tất cả lớp</option>${[1,2,3,4,5].map(g=>`<option>${g}</option>`).join("")}</select><select id="levelFilter"><option value="">Mọi mức độ</option><option>Dễ</option><option>Trung bình</option><option>Khó</option></select></section><section class="subject-grid compact">${D.subjects.map(s=>`<button class="subject-filter ${s.color}" data-filter-subject="${s.id}"><span>${s.icon}</span><b>${s.name}</b></button>`).join("")}</section><div id="lessonResults" class="list-card">${D.lessons.map(lessonRow).join("")}</div>`}
function tests(){return pageHead("KIỂM TRA","Đề luyện tập & thi thử","Có chấm điểm và lưu lịch sử.")+`<div class="cards-3">${D.tests.map(t=>{const s=subj(t.subject);return `<article class="test-card"><div class="test-top"><span class="subject-icon mini ${s.color}">${s.icon}</span><span class="badge">${t.difficulty||"Luyện tập"}</span></div><h3>${esc(t.title)}</h3><p>${s.name} • Lớp ${t.grade}</p><div class="test-meta"><span>⏱ ${t.time} phút</span><span>❓ ${t.count} câu</span></div><button class="primary full" data-start="${t.subject}" data-grade="${t.grade}">Bắt đầu</button></article>`}).join("")}</div>`}
function materials(){return pageHead("TÀI LIỆU","Kho tài liệu","Giáo viên/Admin có thể tải PDF, ảnh và audio lên backend.")+`<div class="panel teacher-only"><h3>⬆️ Upload tài liệu</h3><form id="uploadForm" class="stack"><label>Tiêu đề<input name="title" required></label><label>File<input id="uploadFile" type="file" accept=".pdf,image/png,image/jpeg,audio/mpeg,audio/wav" required></label><button class="primary">Tải lên</button></form></div><div class="list-card" id="materialList">${D.materials.map(m=>`<div class="material-row"><div class="pdf">PDF</div><div class="grow"><b>${esc(m.title)}</b><small>${m.subject||""} • Lớp ${m.grade||""} • ${m.size||""}</small></div><button class="outline">Xem</button></div>`).join("")}</div>`}
function favorites(){const a=D.lessons.filter(x=>state.favorites.includes(x.id));return pageHead("ĐÃ LƯU","Yêu thích")+`<div class="list-card">${a.length?a.map(lessonRow).join(""):'<div class="empty">Chưa có bài yêu thích.</div>'}</div>`}
function history(){const a=[...state.results].reverse(),avg=a.length?Math.round(a.reduce((x,y)=>x+y.score,0)/a.length):0;return pageHead("TIẾN ĐỘ","Kết quả học tập")+`<div class="metrics">${metric("📝",a.length,"Lượt làm")}${metric("🎯",avg+"%","Trung bình")}${metric("⭐",a.reduce((x,y)=>x+(y.points||0),0),"Điểm thưởng")}${metric("⏱",Math.round(a.reduce((x,y)=>x+(y.durationSec||0),0)/60)+"p","Thời gian")}</div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Bài</th><th>Môn</th><th>Điểm</th><th>Ngày</th></tr></thead><tbody>${a.map(r=>`<tr><td>${esc(r.title)}</td><td>${subj(r.subject).name}</td><td><b>${r.score}%</b></td><td>${r.date||""}</td></tr>`).join("")||'<tr><td colspan="4">Chưa có dữ liệu.</td></tr>'}</tbody></table></div></div>`}
async function analytics(){if(!state.user)return loginRequired("Đăng nhập để xem phân tích.");let j;try{j=await API.get("/api/analytics")}catch(e){return errorBox(e.message)}return pageHead("PHÂN TÍCH","Điểm mạnh & điểm cần ôn","Dữ liệu tính từ kết quả đã lưu trên server.")+`<div class="metrics">${metric("📝",j.totalAttempts,"Lượt làm")}${metric("🎯",j.average+"%","Trung bình")}${metric("⏱",j.totalMinutes,"Phút học")}${metric("💡",j.weakest?.name||"—","Môn cần ôn")}</div><div class="panel"><h3>Theo môn</h3>${j.subjects.map(s=>`<div class="simple-row"><span>${subj(s.id).icon}</span><div class="grow"><b>${s.name}</b><small>${s.attempts} lượt • ${s.wrong} câu sai</small></div><strong>${s.avg}%</strong></div>`).join("")||"<p>Chưa có dữ liệu.</p>"}</div>`}
function loginRequired(msg="Bạn cần đăng nhập."){return `<div class="empty large"><h2>🔐 ${msg}</h2><button class="primary" id="openLogin">Đăng nhập / Đăng ký</button></div>`}
function errorBox(m){return `<div class="empty large"><h2>⚠️ Có lỗi</h2><p>${esc(m)}</p></div>`}
async function classes(){if(!state.user)return loginRequired();let j;try{j=await API.get("/api/classes")}catch(e){return errorBox(e.message)}const canCreate=["teacher","admin"].includes(state.user.role);return pageHead("LỚP HỌC","Lớp học của bạn","Giáo viên tạo lớp bằng mã, học sinh nhập mã để tham gia.")+`${canCreate?'<div class="panel"><h3>➕ Tạo lớp</h3><form id="classForm" class="form-grid"><label>Tên lớp<input name="name" required></label><label>Khối<select name="grade">'+[1,2,3,4,5].map(g=>'<option>'+g+'</option>').join('')+'</select></label><button class="primary">Tạo lớp</button></form></div>':''}${state.user.role==="student"?'<div class="panel"><h3>🔑 Vào lớp bằng mã</h3><form id="joinClassForm" class="chat-input"><input name="code" placeholder="Nhập mã lớp" required><button class="primary">Tham gia</button></form></div>':''}<div class="cards-3">${j.classes.map(c=>`<article class="test-card"><h3>🏫 ${esc(c.name)}</h3><p>Lớp ${c.grade}</p><div class="test-meta"><span>Mã: <b>${c.code}</b></span><span>👥 ${c.studentIds?.length||0}</span></div></article>`).join("")||'<div class="empty">Chưa có lớp học.</div>'}</div>`}
async function assignments(){if(!state.user)return loginRequired();let j,cls;try{[j,cls]=await Promise.all([API.get("/api/assignments"),API.get("/api/classes")])}catch(e){return errorBox(e.message)}const teacher=["teacher","admin"].includes(state.user.role);return pageHead("BÀI ĐƯỢC GIAO","Assignments","Giáo viên đặt deadline và giới hạn số lần nộp.")+`${teacher?'<div class="panel"><h3>➕ Giao bài</h3><form id="assignmentForm" class="stack"><label>Lớp<select name="classId">'+cls.classes.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('')+'</select></label><div class="form-grid"><label>Tiêu đề<input name="title" required></label><label>Môn<select name="subject">'+D.subjects.map(s=>'<option value="'+s.id+'">'+s.name+'</option>').join('')+'</select></label><label>Deadline<input type="datetime-local" name="deadline"></label><label>Số lần nộp<input type="number" min="1" value="1" name="maxAttempts"></label></div><button class="primary">Giao bài</button></form></div>':''}<div class="list-card">${j.assignments.map(a=>`<div class="lesson-row"><div class="lesson-ico">📌</div><div class="grow"><b>${esc(a.title)}</b><small>${subj(a.subject).name} • deadline: ${a.deadline?new Date(a.deadline).toLocaleString("vi-VN"):"Không giới hạn"} • tối đa ${a.maxAttempts} lần</small></div>${state.user.role==="student"?`<button class="primary small" data-submit-assignment="${a.id}" data-assignment-subject="${a.subject}">Làm bài</button>`:""}</div>`).join("")||'<div class="empty">Chưa có bài được giao.</div>'}</div>`}
async function notifications(){if(!state.user)return loginRequired();let j;try{j=await API.get("/api/notifications")}catch(e){return errorBox(e.message)}return pageHead("THÔNG BÁO","Trung tâm thông báo")+`<div class="list-card">${j.notifications.map(n=>`<div class="simple-row"><span>🔔</span><div class="grow"><b>${esc(n.title)}</b><small>${esc(n.message)} • ${new Date(n.createdAt).toLocaleString("vi-VN")}</small></div></div>`).join("")||'<div class="empty">Chưa có thông báo.</div>'}</div>`}
async function ai(){return pageHead("TRỢ GIẢNG","🤖 AI học tập","Khi server được cấu hình AI_API_URL/API_KEY, câu hỏi sẽ gửi đến provider thật.")+`<div class="ai-layout"><div class="chat-card"><div class="chat-box" id="chatBox"><div class="msg bot">Chào em! Cô sẽ hướng dẫn từng bước. Em hỏi bài nhé.</div></div><form id="aiForm" class="chat-input"><input id="aiInput" placeholder="Ví dụ: Giải thích phân số 1/2"><button class="primary">Gửi</button></form></div><div class="panel"><h3>Gợi ý</h3>${["Giải thích phép cộng có nhớ","Cho 3 câu Toán lớp 1","Present Simple là gì?","Ôn lại câu em thường sai"].map(x=>`<button class="suggestion" data-prompt="${x}">${x}</button>`).join("")}</div></div>`}
function profile(){if(!state.user)return loginRequired();const u=state.user;return pageHead("TÀI KHOẢN","Hồ sơ")+`<div class="profile-card"><div class="avatar huge">${u.avatar}</div><div><h2>${esc(u.name)}</h2><p>${esc(u.email)}</p><span class="badge">${u.role} ${u.grade?"• Lớp "+u.grade:""}</span></div></div><div class="panel"><h3>Bảo mật tài khoản</h3><p>Email: <b>${u.emailVerified?"Đã xác minh":"Chưa xác minh"}</b></p>${!u.emailVerified?'<button class="primary" id="verifyEmail">Xác minh email (demo backend)</button>':""}</div>`}
async function parent(){if(!state.user||!["parent","admin"].includes(state.user.role))return loginRequired("Đăng nhập tài khoản phụ huynh.");let a=await analytics();return pageHead("PHỤ HUYNH","Theo dõi con","Liên kết bằng email tài khoản học sinh.")+`<div class="panel"><h3>🔗 Liên kết thêm học sinh</h3><form id="linkChildForm" class="chat-input"><input name="studentEmail" type="email" placeholder="Email học sinh" required><button class="primary">Liên kết</button></form></div>`+a}
async function teacher(){if(!state.user||!["teacher","admin"].includes(state.user.role))return loginRequired("Đăng nhập tài khoản giáo viên.");return pageHead("GIÁO VIÊN","Bảng điều khiển giáo viên","Tạo lớp, giao bài, chấm bài và gửi thông báo.")+`<div class="admin-actions"><button class="outline" data-route="classes">🏫 Quản lý lớp</button><button class="outline" data-route="assignments">📌 Giao bài</button><button class="outline" data-route="materials">📎 Tài liệu</button><button class="outline" data-route="notifications">🔔 Thông báo</button></div>`}
async function admin(){if(state.user?.role!=="admin")return loginRequired("Chỉ Admin được truy cập.");let j;try{j=await API.get("/api/admin/stats")}catch(e){return errorBox(e.message)}return pageHead("QUẢN TRỊ","Admin Dashboard","Thống kê và audit log phía server.")+`<div class="metrics">${metric("👥",j.users,"Người dùng")}${metric("🧒",j.students,"Học sinh")}${metric("👩🏻‍🏫",j.teachers,"Giáo viên")}${metric("🏫",j.classes,"Lớp")}</div><div class="metrics">${metric("📌",j.assignments,"Bài giao")}${metric("📨",j.submissions,"Bài nộp")}${metric("📎",j.materials,"Tài liệu")}${metric("🛡️",j.audit.length,"Audit gần đây")}</div><div class="panel"><h3>🔐 Bảo mật Admin</h3><button class="outline" id="setup2fa">Thiết lập 2FA</button><div id="twofaInfo" class="tiny"></div></div><div class="panel"><h3>Audit log</h3><div class="table-wrap"><table><thead><tr><th>Thời gian</th><th>Action</th><th>User</th></tr></thead><tbody>${j.audit.map(a=>`<tr><td>${new Date(a.at).toLocaleString("vi-VN")}</td><td>${a.action}</td><td>${a.userId||"system"}</td></tr>`).join("")}</tbody></table></div></div>`}
function achievements(){return pageHead("THÀNH TÍCH","Huy hiệu & XP")+`<div class="badge-grid">${[["🌱","Khởi đầu"],["🔥","Chăm chỉ"],["⭐","100 điểm"],["🏆","Siêu học sinh"],["🎯","Chính xác"],["📚","Mọt sách"]].map((b,i)=>`<article class="achievement ${state.results.length>i?"unlocked":"locked"}"><div>${b[0]}</div><h3>${b[1]}</h3><p>Tiếp tục học để mở khóa.</p></article>`).join("")}</div>`}
function shop(){return pageHead("GAMIFICATION","Shop & phần thưởng","Khung chức năng XP/avatar; dữ liệu thanh toán Premium chưa bật nếu chưa cấu hình provider.")+`<div class="cards-3">${["🎓 Khung học giỏi","🐼 Thú cưng Panda","🌟 Avatar sao","🚀 Booster XP"].map((x,i)=>`<article class="test-card"><h3>${x}</h3><p>${(i+1)*100} XP</p><button class="outline">Đổi thưởng</button></article>`).join("")}</div>`}

function flashcards(){const cards=D.lessons.slice(0,8);return pageHead("FLASHCARD","Ôn nhanh kiến thức","Bấm vào thẻ để lật mặt sau, dùng giọng đọc của trình duyệt nếu cần.")+`<div class="cards-3">${cards.map((l,i)=>`<button class="test-card flashcard" data-flash="${i}" data-front="${esc(l.title)}" data-back="${esc(subj(l.subject).name+" • "+(l.topic||"Kiến thức trọng tâm"))}"><div class="subject-icon">${subj(l.subject).icon}</div><h3>${esc(l.title)}</h3><p>Chạm để lật</p></button>`).join("")}</div><div class="panel"><button class="outline" id="readFlash">🔊 Đọc thẻ đầu tiên</button></div>`}
function game(){return pageHead("MINI GAME","⚡ Toán nhanh","Trả lời liên tục để tăng combo và XP.")+`<div class="result-card"><div class="score-ring"><b id="gameScore">0</b><span>XP</span></div><div class="question-card"><h2 id="gameQ">Bấm Bắt đầu</h2><div class="options" id="gameOptions"></div></div><div class="quiz-actions"><button class="primary" id="startGame">Bắt đầu game</button></div></div>`}
async function submissions(){if(!state.user||!["teacher","admin"].includes(state.user.role))return loginRequired("Chỉ giáo viên/Admin được xem bài nộp.");let j;try{j=await API.get("/api/submissions")}catch(e){return errorBox(e.message)}return pageHead("CHẤM BÀI","Bài học sinh đã nộp","Chỉnh điểm và nhận xét trực tiếp.")+`<div class="list-card">${j.submissions.map(x=>`<div class="lesson-row"><div class="lesson-ico">📨</div><div class="grow"><b>${esc(x.student?.name||"Học sinh")} — ${esc(x.assignment?.title||"Bài tập")}</b><small>Điểm: ${x.score}% • ${new Date(x.submittedAt).toLocaleString("vi-VN")}</small></div><button class="outline small" data-grade-submission="${x.id}" data-current-score="${x.score}">Chấm</button></div>`).join("")||'<div class="empty">Chưa có bài nộp.</div>'}</div>`}
async function premium(){let i={premium:false};try{i=await API.get("/api/integrations")}catch{}return pageHead("PREMIUM","Nâng cấp tài khoản","Checkout chỉ hoạt động khi server được cấu hình PAYMENT_CHECKOUT_URL.")+`<div class="cards-3"><article class="test-card"><h3>Free</h3><p>Bài tập cơ bản, lịch sử học, lớp học.</p><button class="outline full" disabled>Đang dùng</button></article><article class="test-card"><h3>⭐ Premium</h3><p>Khung cho tài liệu nâng cao, AI quota, báo cáo mở rộng.</p><button class="primary full" id="premiumBtn" ${i.premium?"":"disabled"}>${i.premium?"Thanh toán an toàn":"Chưa cấu hình cổng thanh toán"}</button></article></div>`}
function renderSync(){const map={home,subjects,tests,materials,favorites,history,ai,profile,achievements,shop,flashcards,game};$("#content").innerHTML=(map[state.route]||home)();bind()}
async function render(){shell();const asyncMap={classes,assignments,notifications,analytics,parent,teacher,admin,submissions,premium};if(asyncMap[state.route]){$("#content").innerHTML='<div class="empty">Đang tải...</div>';$("#content").innerHTML=await asyncMap[state.route]();bind()}else renderSync();shell()}
function filterLessons(){const q=norm($("#lessonSearch")?.value),g=$("#gradeFilter")?.value||"",lv=$("#levelFilter")?.value||"",s=state.subjectFilter;const a=D.lessons.filter(l=>(!q||norm(l.title+" "+subj(l.subject).name+" "+(l.topic||"")).includes(q))&&(!g||String(l.grade)===g)&&(!lv||l.level===lv)&&(!s||l.subject===s));$("#lessonResults").innerHTML=a.map(lessonRow).join("")||'<div class="empty">Không tìm thấy.</div>';bind()}
function startQuiz(subject,grade,assignmentId=null){let qs=D.questions.filter(q=>q.subject===subject&&q.grade===grade);if(!qs.length)qs=D.questions.filter(q=>q.subject===subject);if(!qs.length)qs=D.questions.slice(0,5);state.quiz={subject,grade,assignmentId,questions:qs.slice(0,8),i:0,answers:{},start:Date.now()};localStorage.setItem("bt_quiz",JSON.stringify(state.quiz));quiz()}
function quiz(){const z=state.quiz,q=z.questions[z.i];$("#content").innerHTML=`<section class="quiz-shell"><div class="quiz-head"><div><span class="badge">${subj(z.subject).name} • Lớp ${z.grade}</span><h2>Câu ${z.i+1}/${z.questions.length}</h2></div><div id="timer">⏱</div></div><div class="progress"><span style="width:${(z.i+1)/z.questions.length*100}%"></span></div><article class="question-card"><h2>${esc(q.q)}</h2><div class="options">${q.options.map((o,i)=>`<button class="${z.answers[q.id]===i?"selected":""}" data-answer="${i}"><span>${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join("")}</div></article><div class="quiz-actions"><button class="outline" id="prevQ" ${z.i===0?"disabled":""}>← Trước</button><button class="primary" id="${z.i===z.questions.length-1?"finishQuiz":"nextQ"}">${z.i===z.questions.length-1?"Nộp bài":"Tiếp →"}</button></div></section>`;$$("[data-answer]").forEach(b=>b.onclick=()=>{z.answers[q.id]=Number(b.dataset.answer);localStorage.setItem("bt_quiz",JSON.stringify(z));quiz()});$("#prevQ").onclick=()=>{z.i--;quiz()};$("#nextQ")?.addEventListener("click",()=>{z.i++;quiz()});$("#finishQuiz")?.addEventListener("click",finishQuiz)}
async function finishQuiz(){const z=state.quiz;let correct=0,wrong=[];z.questions.forEach(q=>{if(z.answers[q.id]===q.answer)correct++;else wrong.push(q.id)});const score=Math.round(correct/z.questions.length*100),durationSec=Math.round((Date.now()-z.start)/1000),r={id:Date.now(),title:`${subj(z.subject).name} lớp ${z.grade}`,subject:z.subject,grade:z.grade,correct,total:z.questions.length,score,points:correct*10,durationSec,date:new Date().toLocaleDateString("vi-VN")};state.results.push(r);saveLocal();if(state.user?.role==="student"){try{await API.post("/api/results",{...r,wrongQuestionIds:wrong});if(z.assignmentId)await API.post("/api/assignments/"+z.assignmentId+"/submit",{answers:z.answers,score})}catch(e){toast("Đã lưu local; server: "+e.message)}}$("#content").innerHTML=`<section class="result-card"><div class="score-ring"><b>${score}%</b><span>${correct}/${z.questions.length} đúng</span></div><h1>${score>=80?"Xuất sắc 🎉":score>=50?"Làm tốt 👍":"Ôn thêm nhé 💪"}</h1><div class="result-review">${z.questions.map((q,i)=>`<div class="review ${z.answers[q.id]===q.answer?"":"bad"}"><b>Câu ${i+1}: ${esc(q.q)}</b><p>Đáp án đúng: ${esc(q.options[q.answer])}</p><small>💡 ${esc(q.explain||"")}</small></div>`).join("")}</div><button class="primary" id="goHistory">Xem kết quả</button></section>`;$("#goHistory").onclick=()=>nav("history");state.quiz=null;localStorage.removeItem("bt_quiz")}
function openAuth(){const m=$("#modal"),w=$("#modalBackdrop");w.classList.remove("hidden");m.innerHTML=`<button class="modal-x" id="closeModal">×</button><div class="auth-icon">🎓</div><h2>Đăng nhập / Đăng ký</h2><div class="tabs"><button class="outline" id="tabLogin">Đăng nhập</button><button class="outline" id="tabRegister">Đăng ký</button></div><div id="authPane"></div>`;$("#closeModal").onclick=()=>w.classList.add("hidden");$("#tabLogin").onclick=loginForm;$("#tabRegister").onclick=registerForm;loginForm()}
function loginForm(){$("#authPane").innerHTML=`<form id="loginForm" class="stack"><label>Email<input name="email" type="email" required></label><label>Mật khẩu<input name="password" type="password" required></label><label>Mã 2FA (nếu Admin đã bật)<input name="otp" inputmode="numeric" maxlength="6" placeholder="123456"></label><button class="primary">Đăng nhập</button><a class="outline" href="/api/google/auth">🔵 Đăng nhập với Google</a><button type="button" class="link-btn" id="forgotBtn">Quên mật khẩu?</button></form><p class="tiny">Nếu chạy với SEED_DEMO=1: hocsinh@demo.vn / giaovien@demo.vn / phuhuynh@demo.vn / admin@demo.vn — mật khẩu Demo1234!</p>`;$("#loginForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{const j=await API.post("/api/login",d);API.setToken(j.token);state.user=j.user;$("#modalBackdrop").classList.add("hidden");toast("Đăng nhập thành công");render()}catch(x){toast(x.message)}};$("#forgotBtn").onclick=forgotForm}
function registerForm(){$("#authPane").innerHTML=`<form id="registerForm" class="stack"><label>Họ tên<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Mật khẩu<input type="password" name="password" minlength="8" required></label><div class="form-grid"><label>Vai trò<select name="role"><option value="student">Học sinh</option><option value="parent">Phụ huynh</option><option value="teacher">Giáo viên</option></select></label><label>Lớp<select name="grade">${[1,2,3,4,5].map(x=>'<option>'+x+'</option>').join("")}</select></label></div><button class="primary">Tạo tài khoản</button></form>`;$("#registerForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{await API.post("/api/register",d);toast("Đăng ký thành công, hãy đăng nhập");loginForm()}catch(x){toast(x.message)}}}
function forgotForm(){$("#authPane").innerHTML=`<form id="forgotForm" class="stack"><label>Email<input type="email" name="email" required></label><button class="primary">Tạo yêu cầu đặt lại mật khẩu</button></form>`;$("#forgotForm").onsubmit=async e=>{e.preventDefault();try{const j=await API.post("/api/forgot-password",Object.fromEntries(new FormData(e.currentTarget)));$("#authPane").innerHTML='<p>'+esc(j.message)+'</p>'+(j.resetToken?'<p class="tiny">Dev token: '+esc(j.resetToken)+'</p>':'')}catch(x){toast(x.message)}}}
function bind(){
 $$("[data-route]").forEach(x=>x.onclick=()=>nav(x.dataset.route));$$("[data-subject]").forEach(x=>x.onclick=()=>{state.subjectFilter=x.dataset.subject;nav("subjects")});$$("[data-fav]").forEach(x=>x.onclick=()=>{const id=Number(x.dataset.fav);state.favorites=state.favorites.includes(id)?state.favorites.filter(a=>a!==id):[...state.favorites,id];saveLocal();render()});$$("[data-start]").forEach(x=>x.onclick=()=>startQuiz(x.dataset.start,Number(x.dataset.grade)));$("#openLogin")?.addEventListener("click",openAuth);
 $("#globalSearchBtn")?.addEventListener("click",()=>{const q=$("#globalSearch").value;nav("subjects");setTimeout(()=>{$("#lessonSearch").value=q;filterLessons()},20)});$$(".quick-grades [data-grade]").forEach(x=>x.onclick=()=>{nav("subjects");setTimeout(()=>{$("#gradeFilter").value=x.dataset.grade;filterLessons()},20)});
 ["lessonSearch","gradeFilter","levelFilter"].forEach(id=>$("#"+id)?.addEventListener("input",filterLessons));$$("[data-filter-subject]").forEach(x=>x.onclick=()=>{state.subjectFilter=x.dataset.filterSubject;filterLessons()});
 $("#classForm")?.addEventListener("submit",async e=>{e.preventDefault();try{await API.post("/api/classes",Object.fromEntries(new FormData(e.currentTarget)));toast("Đã tạo lớp");render()}catch(x){toast(x.message)}});
 $("#joinClassForm")?.addEventListener("submit",async e=>{e.preventDefault();try{await API.post("/api/classes/join",Object.fromEntries(new FormData(e.currentTarget)));toast("Đã tham gia lớp");render()}catch(x){toast(x.message)}});
 $("#assignmentForm")?.addEventListener("submit",async e=>{e.preventDefault();try{await API.post("/api/assignments",Object.fromEntries(new FormData(e.currentTarget)));toast("Đã giao bài");render()}catch(x){toast(x.message)}});
 $$("[data-submit-assignment]").forEach(x=>x.onclick=()=>startQuiz(x.dataset.assignmentSubject,state.user?.grade||1,x.dataset.submitAssignment));
 $("#uploadForm")?.addEventListener("submit",async e=>{e.preventDefault();const f=$("#uploadFile").files[0];if(!f)return;const rd=new FileReader();rd.onload=async()=>{try{await API.post("/api/upload",{title:new FormData(e.currentTarget).get("title"),dataUrl:rd.result});toast("Upload thành công");render()}catch(x){toast(x.message)}};rd.readAsDataURL(f)});
 $("#aiForm")?.addEventListener("submit",async e=>{e.preventDefault();const t=$("#aiInput").value.trim();if(!t)return;const box=$("#chatBox");box.innerHTML+=`<div class="msg user">${esc(t)}</div>`;$("#aiInput").value="";try{const j=await API.post("/api/ai",{prompt:t});box.innerHTML+=`<div class="msg bot">${esc(j.answer)}</div>`}catch(x){box.innerHTML+=`<div class="msg bot">⚠️ ${esc(x.message)}</div>`}box.scrollTop=box.scrollHeight});$$("[data-prompt]").forEach(x=>x.onclick=()=>{$("#aiInput").value=x.dataset.prompt;$("#aiForm").requestSubmit()});
 $("#verifyEmail")?.addEventListener("click",async()=>{try{const j=await API.post("/api/verify-email",{});state.user=j.user;toast("Đã xác minh");render()}catch(x){toast(x.message)}});\n $("#setup2fa")?.addEventListener("click",async()=>{try{const j=await API.post("/api/2fa/setup",{});$("#twofaInfo").innerHTML="<p>Secret: <code>"+esc(j.secret)+"</code></p><p>Thêm secret này vào ứng dụng Authenticator, sau đó nhập mã 6 số:</p><div class='chat-input'><input id='twofaCode' maxlength='6' inputmode='numeric'><button class='primary' id='enable2fa'>Bật 2FA</button></div>";$("#enable2fa").onclick=async()=>{try{await API.post("/api/2fa/enable",{code:$("#twofaCode").value});toast("Đã bật 2FA")}catch(x){toast(x.message)}}}catch(x){toast(x.message)}});
 shell()
}
$("#menuBtn")?.addEventListener("click",()=>$("#sidebar").classList.toggle("open"));
$("#themeBtn")?.addEventListener("click",()=>{state.theme=state.theme==="light"?"dark":"light";document.documentElement.dataset.theme=state.theme;localStorage.setItem("bt_theme",state.theme)});
$("#authBtn")?.addEventListener("click",async()=>{if(state.user){try{await API.post("/api/logout",{})}catch{}API.setToken("");state.user=null;nav("home")}else openAuth()});
window.addEventListener("hashchange",()=>{state.route=location.hash.slice(1)||"home";render()});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("/sw.js").catch(()=>{}));
const qp=new URLSearchParams(location.search);if(qp.get("auth_token")){API.setToken(qp.get("auth_token"));history.replaceState(null,"",location.pathname+location.hash)}const savedQuiz=localStorage.getItem("bt_quiz");if(savedQuiz){try{state.quiz=JSON.parse(savedQuiz)}catch{}}restore().then(render);
})();