const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto"),url=require("url"),staticServer=require("./lib/static-server");
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,STATIC_ROOT=process.env.STATIC_ROOT||((process.env.NODE_ENV==="production"&&fs.existsSync(path.join(ROOT,"dist")))?path.join(ROOT,"dist"):ROOT),DB_PATH=path.join(ROOT,"data","db.json"),UPLOAD_DIR=path.join(ROOT,"uploads");
const TOKEN_TTL=7*864e5,RESET_TTL=30*60e3,MAX_BODY=2e6;
const rateBuckets=new Map(),resetTokens=new Map(),oauthStates=new Map();
const pgStore=require("./lib/postgres"),storage=require("./lib/storage"),sessionStore=require("./lib/redis-session"),supabase=require("./lib/supabase-admin"),monitor=require("./lib/monitoring"),handleStudent=require("./routes/student"),handleApp=require("./routes/app"),handleExamSettings=require("./routes/exam-settings"),handleSupabaseAuth=require("./routes/supabase-auth"),handleAccount=require("./routes/account"),handleCaptcha=require("./routes/captcha"),handleStorageMeta=require("./routes/storage-meta"),handleHealth=require("./routes/health"),handleAI=require("./routes/ai"),handleExamDrafts=require("./routes/exam-drafts"),handleMetrics=require("./routes/metrics"),errorTracking=require("./lib/error-tracking"),auditStore=require("./lib/audit"),{verify:verifyTotp,secret:newTotpSecret}=require("./lib/totp");

function load(){return storage.load()}
function save(db){return storage.save(db)}
function id(){return crypto.randomUUID()}
function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){return salt+":"+crypto.scryptSync(password,salt,64).toString("hex")}
function verifyPassword(password,stored=""){try{const [salt,hex]=stored.split(":");const a=Buffer.from(hex,"hex"),b=crypto.scryptSync(password,salt,64);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
function safeUser(u){if(!u)return null;return {id:u.id,name:u.name,email:u.email,role:u.role,grade:u.grade||null,avatar:u.avatar||"👧🏻",emailVerified:!!u.emailVerified,createdAt:u.createdAt}}
function send(res,code,obj,extra={}){res.writeHead(code,{"Content-Type":"application/json; charset=utf-8","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"strict-origin-when-cross-origin","Permissions-Policy":"camera=(), geolocation=(), microphone=(self)",...extra});res.end(JSON.stringify(obj))}
function parseBody(req){return new Promise((resolve,reject)=>{let d="";req.on("data",c=>{d+=c;if(d.length>MAX_BODY){reject(new Error("too_large"));req.destroy()}});req.on("end",()=>{try{resolve(JSON.parse(d||"{}"))}catch{reject(new Error("bad_json"))}})})}
function token(req){return (req.headers.authorization||"").replace(/^Bearer\s+/i,"")}
async function auth(req){
 const t=token(req);if(!t)return null;
 const ss=await sessionStore.get(t);
 if(ss&&ss.exp>=Date.now())return load().users.find(x=>x.id===ss.uid)||null;
 if(ss&&ss.exp<Date.now())await sessionStore.del(t);
 if(supabase.enabled()){
  const su=await supabase.getUserFromToken(t);
  if(su){
   const db=load();let u=db.users.find(x=>x.authUserId===su.id||String(x.email||"").toLowerCase()===String(su.email||"").toLowerCase());
   if(u){u.authUserId=su.id;u.emailVerified=!!su.email_confirmed_at;save(db);return u}
  }
 }
 return null
}
async function requireUser(req,res,roles){const u=await auth(req);if(!u){send(res,401,{error:"Bạn cần đăng nhập"});return null}if(u.locked){send(res,423,{error:"Tài khoản đã bị khóa"});return null}if(roles&&!roles.includes(u.role)){send(res,403,{error:"Bạn không có quyền thực hiện"});return null}return u}
function rate(ip,key="global",limit=80,windowMs=60e3){const k=ip+":"+key,now=Date.now(),arr=(rateBuckets.get(k)||[]).filter(t=>now-t<windowMs);arr.push(now);rateBuckets.set(k,arr);return arr.length<=limit}
function audit(db,user,action,meta={}){return auditStore.record(db,user,action,meta)}
function subjectName(id){return ({math:"Toán",vietnamese:"Tiếng Việt",english:"Tiếng Anh",nature:"Tự nhiên & Xã hội",science:"Khoa học",history:"Lịch sử & Địa lý"})[id]||id}
function normalize(s=""){return String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function pageList(list,req,{searchFn}={}){
 const q=url.parse(req.url,true).query||{},search=normalize(q.search||"");let rows=[...list];
 if(search&&searchFn)rows=rows.filter(x=>normalize(searchFn(x)).includes(search));
 const limit=Math.max(1,Math.min(100,Number(q.limit)||30)),page=Math.max(1,Number(q.page)||1),total=rows.length,start=(page-1)*limit;
 return {items:rows.slice(start,start+limit),pagination:{page,limit,total,pages:Math.ceil(total/limit),hasMore:start+limit<total},search}
}
function mime(file){return ({".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".svg":"image/svg+xml",".pdf":"application/pdf",".webmanifest":"application/manifest+json"})[path.extname(file).toLowerCase()]||"application/octet-stream"}

function routeMatch(p,pattern){const a=p.split("/").filter(Boolean),b=pattern.split("/").filter(Boolean);if(a.length!==b.length)return null;const params={};for(let i=0;i<b.length;i++){if(b[i].startsWith(":"))params[b[i].slice(1)]=decodeURIComponent(a[i]);else if(a[i]!==b[i])return null}return params}
function seedAdmin(){const db=load();if(!db.users.length&&process.env.SEED_DEMO==="1"&&process.env.NODE_ENV!=="production"){const now=new Date().toISOString();db.users.push(
{id:"demo-student",name:"Bé Minh Anh",email:"hocsinh@demo.vn",password:hashPassword("Demo1234!"),role:"student",grade:3,avatar:"👧🏻",emailVerified:true,createdAt:now},
{id:"demo-teacher",name:"Cô Lan",email:"giaovien@demo.vn",password:hashPassword("Demo1234!"),role:"teacher",avatar:"👩🏻‍🏫",emailVerified:true,createdAt:now},
{id:"demo-parent",name:"Phụ huynh Minh Anh",email:"phuhuynh@demo.vn",password:hashPassword("Demo1234!"),role:"parent",avatar:"👩🏻",emailVerified:true,children:["demo-student"],createdAt:now},
{id:"demo-admin",name:"Quản trị viên",email:"admin@demo.vn",password:hashPassword(crypto.randomBytes(32).toString("hex")),role:"admin",avatar:"🧑🏻‍💻",emailVerified:true,createdAt:now});save(db)}}

async function api(req,res,p,ip){
 if(await handleHealth(req,res,p,{send,storage,pg:pgStore,supabase}))return;
 if(["/api/metrics","/api/client-errors"].includes(p)&&!rate(ip,"telemetry",30,60e3))return send(res,429,{error:"Too many metrics"});
 if(await handleMetrics(req,res,p,{send,parseBody,monitor}))return;
 if(!rate(ip,"api",180,60e3))return send(res,429,{error:"Bạn thao tác quá nhanh"});
 if(req.method==="POST"&&["/api/ai","/api/ai/analyze-wrong"].includes(p)&&!rate(ip,"ai",24,60e3))return send(res,429,{error:"AI đang bận, thử lại sau"});
 if(req.method==="POST"&&p==="/api/student/ocr"&&!rate(ip,"ocr",10,60e3))return send(res,429,{error:"OCR đang bận, thử lại sau"});
 if(req.method==="POST"&&(p.startsWith("/api/storage/")||p==="/api/student/handwriting")&&!rate(ip,"upload",20,60e3))return send(res,429,{error:"Bạn tải file quá nhanh"});
 if(await handleAI(req,res,p,{send,parseBody,requireUser,monitor}))return;
 if(await handleExamDrafts(req,res,p,{send,parseBody,requireUser,load,save}))return;
 if(await handleSupabaseAuth(req,res,p,{send,parseBody,load,save,supabase,monitor,pg:pgStore}))return;
 if(await handleAccount(req,res,p,{send,requireUser,load,save,supabase,monitor,audit:auditStore}))return;
 if(await handleCaptcha(req,res,p,{send,parseBody}))return;
 if(await handleStorageMeta(req,res,p,{send,parseBody,requireUser,load,save,monitor,audit:auditStore}))return;
 if(await handleApp(req,res,p,{send,parseBody,requireUser,load,save,ROOT}))return;
 if(await handleExamSettings(req,res,p,{send,parseBody,requireUser,load,save,ROOT,audit:auditStore}))return;
 if(await handleStudent(req,res,p,{send,parseBody,requireUser,load,save,ROOT}))return;
 if(req.method==="POST"&&p==="/api/register"){if(!rate(ip,"auth",10,10*60e3))return send(res,429,{error:"Thử lại sau"});let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}
  const email=String(d.email||"").trim().toLowerCase(),password=String(d.password||""),role=["student","parent"].includes(d.role)?d.role:"student";
  if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return send(res,400,{error:"Email hợp lệ và mật khẩu tối thiểu 8 ký tự"});
  const db=load();if(db.users.some(x=>x.email===email))return send(res,409,{error:"Email đã tồn tại"});
  const u={id:id(),name:String(d.name||"Người dùng").slice(0,80),email,password:hashPassword(password),role,grade:role==="student"?Number(d.grade)||1:null,avatar:role==="teacher"?"👩🏻‍🏫":role==="parent"?"👩🏻":"👧🏻",emailVerified:false,createdAt:new Date().toISOString()};db.users.push(u);audit(db,u,"register");save(db);pgStore.upsertUser(u).catch(()=>{});return send(res,201,{user:safeUser(u),message:"Đăng ký thành công"})}
 if(req.method==="POST"&&p==="/api/login"){if(!rate(ip,"login",8,60e3))return send(res,429,{error:"Quá nhiều lần đăng nhập sai"});let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}
  const db=load(),u=db.users.find(x=>x.email===String(d.email||"").trim().toLowerCase());if(!u||!verifyPassword(String(d.password||""),u.password))return send(res,401,{error:"Sai email hoặc mật khẩu"});if(u.totpSecret&&!verifyTotp(u.totpSecret,d.otp))return send(res,401,{error:"Cần mã 2FA hợp lệ",requires2fa:true});
  const t=crypto.randomBytes(32).toString("hex");await sessionStore.set(t,{uid:u.id,exp:Date.now()+TOKEN_TTL},TOKEN_TTL);audit(db,u,"login");save(db);return send(res,200,{token:t,user:safeUser(u)})}
 if(req.method==="POST"&&p==="/api/logout"){await sessionStore.del(token(req));return send(res,200,{ok:true})}
 if(req.method==="GET"&&p==="/api/me"){const u=await requireUser(req,res);if(!u)return;return send(res,200,{user:safeUser(u)})}
 if(req.method==="POST"&&p==="/api/forgot-password"){let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),u=db.users.find(x=>x.email===String(d.email||"").trim().toLowerCase());if(u){const t=crypto.randomBytes(24).toString("hex");resetTokens.set(t,{uid:u.id,exp:Date.now()+RESET_TTL});audit(db,u,"password_reset_requested");save(db);if(process.env.NODE_ENV!=="production"&&process.env.ALLOW_DEV_RESET_TOKEN==="1")return send(res,200,{message:"Mã đặt lại trong môi trường phát triển",resetToken:t})}return send(res,200,{message:"Nếu email tồn tại, hệ thống đã gửi hướng dẫn"})}
 if(req.method==="POST"&&p==="/api/reset-password"){let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const r=resetTokens.get(String(d.token||""));if(!r||r.exp<Date.now())return send(res,400,{error:"Mã đặt lại không hợp lệ hoặc đã hết hạn"});if(String(d.password||"").length<8)return send(res,400,{error:"Mật khẩu tối thiểu 8 ký tự"});const db=load(),u=db.users.find(x=>x.id===r.uid);u.password=hashPassword(String(d.password));resetTokens.delete(String(d.token));audit(db,u,"password_reset");save(db);return send(res,200,{ok:true})}
 if(req.method==="POST"&&p==="/api/verify-email")return send(res,501,{error:"Xác minh email chưa được cấu hình. Không thể tự xác minh."})

 if(req.method==="GET"&&p==="/api/classes"){const u=await requireUser(req,res);if(!u)return;const db=load();const list=u.role==="admin"?db.classes:u.role==="teacher"?db.classes.filter(c=>c.teacherId===u.id):u.role==="student"?db.classes.filter(c=>c.studentIds?.includes(u.id)):db.classes.filter(c=>c.studentIds?.some(s=>u.children?.includes(s)));return send(res,200,{classes:list})}
 if(req.method==="POST"&&p==="/api/classes"){const u=await requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),c={id:id(),name:String(d.name||"Lớp học").slice(0,80),grade:Number(d.grade)||1,teacherId:u.id,code:crypto.randomBytes(3).toString("hex").toUpperCase(),studentIds:[],createdAt:new Date().toISOString()};db.classes.push(c);audit(db,u,"class_created",{classId:c.id});save(db);return send(res,201,{class:c})}
 if(req.method==="POST"&&p==="/api/classes/join"){const u=await requireUser(req,res,["student"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),c=db.classes.find(x=>x.code===String(d.code||"").trim().toUpperCase());if(!c)return send(res,404,{error:"Không tìm thấy mã lớp"});c.studentIds=[...new Set([...(c.studentIds||[]),u.id])];audit(db,u,"class_joined",{classId:c.id});save(db);return send(res,200,{class:c})}

 if(req.method==="GET"&&p==="/api/assignments"){const u=await requireUser(req,res);if(!u)return;const db=load();let list=db.assignments;if(u.role==="teacher")list=list.filter(a=>a.teacherId===u.id);if(u.role==="student"){const classIds=db.classes.filter(c=>c.studentIds?.includes(u.id)).map(c=>c.id);list=list.filter(a=>classIds.includes(a.classId))}return send(res,200,{assignments:list})}
 if(req.method==="POST"&&p==="/api/assignments"){const u=await requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load();if(u.role==="teacher"&&!db.classes.some(c=>c.id===d.classId&&c.teacherId===u.id))return send(res,403,{error:"Không được giao bài vào lớp khác"});const a={id:id(),classId:d.classId,teacherId:u.id,title:String(d.title||"Bài tập"),subject:d.subject||"math",lessonId:String(d.lessonId||""),grade:Number(d.grade)||null,questionIds:Array.isArray(d.questionIds)?d.questionIds:[],deadline:d.deadline||null,maxAttempts:Math.max(1,Number(d.maxAttempts)||1),createdAt:new Date().toISOString()};db.assignments.push(a);audit(db,u,"assignment_created",{assignmentId:a.id});save(db);return send(res,201,{assignment:a})}
 const sub=routeMatch(p,"/api/assignments/:id/submit");if(req.method==="POST"&&sub){const u=await requireUser(req,res,["student"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),a=db.assignments.find(x=>x.id===sub.id);if(!a)return send(res,404,{error:"Không tìm thấy bài giao"});if(!db.classes.some(c=>c.id===a.classId&&c.studentIds?.includes(u.id)))return send(res,403,{error:"Học sinh không thuộc lớp được giao bài"});const attempts=db.submissions.filter(s=>s.assignmentId===a.id&&s.studentId===u.id).length;if(attempts>=a.maxAttempts)return send(res,409,{error:"Đã hết số lần nộp"});const s={id:id(),assignmentId:a.id,studentId:u.id,answers:(d.answers&&typeof d.answers==="object"&&!Array.isArray(d.answers)?d.answers:{}),score:null,gradingStatus:"pending",feedback:"",submittedAt:new Date().toISOString()};db.submissions.push(s);audit(db,u,"assignment_submitted",{assignmentId:a.id,gradingStatus:"pending"});save(db);return send(res,201,{submission:s})}
 const grade=routeMatch(p,"/api/submissions/:id/grade");if(req.method==="PATCH"&&grade){const u=await requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),s=db.submissions.find(x=>x.id===grade.id);if(!s)return send(res,404,{error:"Không tìm thấy bài nộp"});if(u.role==="teacher"&&!db.assignments.some(a=>a.id===s.assignmentId&&a.teacherId===u.id))return send(res,403,{error:"Không được chấm bài giáo viên khác"});if(!Number.isFinite(Number(d.score))||Number(d.score)<0||Number(d.score)>100)return send(res,400,{error:"Điểm phải nằm trong khoảng 0–100"});s.score=Number(d.score);s.gradingStatus="teacher_graded";s.feedback=String(d.feedback||"");s.gradedAt=new Date().toISOString();audit(db,u,"submission_graded",{submissionId:s.id,score:s.score});save(db);return send(res,200,{submission:s})}

 if(req.method==="GET"&&p==="/api/results"){const u=await requireUser(req,res);if(!u)return;const db=load(),q=url.parse(req.url,true).query||{};let list=db.results;if(u.role==="student")list=list.filter(r=>r.userId===u.id);if(u.role==="parent")list=list.filter(r=>u.children?.includes(r.userId));if(u.role==="teacher")list=list.filter(r=>db.classes.some(c=>c.teacherId===u.id&&c.studentIds?.includes(r.userId)));list=[...list].sort((a,b)=>new Date(b.createdAt||b.isoDate||0)-new Date(a.createdAt||a.isoDate||0));const limit=Math.max(1,Math.min(100,Number(q.limit)||50)),page=Math.max(1,Number(q.page)||1),total=list.length,start=(page-1)*limit,items=list.slice(start,start+limit);return send(res,200,{results:items,pagination:{page,limit,total,pages:Math.ceil(total/limit),hasMore:start+limit<total}})}
 if(req.method==="POST"&&p==="/api/results"){const u=await requireUser(req,res,["student"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),clientSubmissionId=String(d.clientSubmissionId||"").slice(0,120);if(clientSubmissionId){const existing=db.results.find(x=>x.userId===u.id&&x.clientSubmissionId===clientSubmissionId);if(existing)return send(res,200,{result:existing,duplicate:true})}const total=Number(d.total),correct=Number(d.correct),score=Number(d.score);if(!Number.isSafeInteger(total)||total<1||total>200||!Number.isSafeInteger(correct)||correct<0||correct>total||!Number.isFinite(score)||score<0||score>100)return send(res,400,{error:"Dữ liệu kết quả không hợp lệ"});const r={id:id(),clientSubmissionId:clientSubmissionId||null,userId:u.id,subject:d.subject||"math",grade:Number(d.grade)||u.grade||1,title:String(d.title||"Bài luyện tập"),score,correct,total,verified:false,gradingStatus:"self_reported",wrongQuestionIds:Array.isArray(d.wrongQuestionIds)?d.wrongQuestionIds.slice(0,200):[],durationSec:Math.max(0,Math.min(86400,Number(d.durationSec)||0)),proctor:d.proctor||null,createdAt:new Date().toISOString()};db.results.push(r);audit(db,u,"result_saved",{score:r.score,verified:false,clientSubmissionId:r.clientSubmissionId});save(db);pgStore.saveResult(r).catch(()=>{});return send(res,201,{result:r})}

 if(req.method==="GET"&&p==="/api/analytics"){const u=await requireUser(req,res);if(!u)return;const db=load();let rs=db.results;if(u.role==="student")rs=rs.filter(r=>r.userId===u.id);if(u.role==="parent")rs=rs.filter(r=>u.children?.includes(r.userId));if(u.role==="teacher")rs=rs.filter(r=>db.classes.some(c=>c.teacherId===u.id&&c.studentIds?.includes(r.userId)));const bySubject={};for(const r of rs){const k=r.subject||"other";bySubject[k]??={count:0,sum:0,wrong:0};bySubject[k].count++;bySubject[k].sum+=r.score;bySubject[k].wrong+=Math.max(0,(r.total||0)-(r.correct||0))}const subjects=Object.entries(bySubject).map(([id,v])=>({id,name:subjectName(id),attempts:v.count,avg:Math.round(v.sum/v.count),wrong:v.wrong})).sort((a,b)=>a.avg-b.avg);return send(res,200,{totalAttempts:rs.length,average:rs.length?Math.round(rs.reduce((a,b)=>a+b.score,0)/rs.length):0,totalMinutes:Math.round(rs.reduce((a,b)=>a+(b.durationSec||0),0)/60),subjects,weakest:subjects[0]||null})}

 if(req.method==="GET"&&p==="/api/notifications"){const u=await requireUser(req,res);if(!u)return;const db=load(),base=db.notifications.filter(n=>!n.userId||n.userId===u.id),pg=pageList(base,req,{searchFn:n=>(n.title||"")+" "+(n.message||"")});return send(res,200,{notifications:pg.items,pagination:pg.pagination})}
 if(req.method==="POST"&&p==="/api/notifications"){const u=await requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),n={id:id(),userId:d.userId||null,title:String(d.title||"Thông báo"),message:String(d.message||""),createdAt:new Date().toISOString()};db.notifications.unshift(n);audit(db,u,"notification_created");save(db);return send(res,201,{notification:n})}

 if(req.method==="POST"&&p==="/api/upload"){const u=await requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const m=String(d.dataUrl||"").match(/^data:(application\/pdf|image\/(?:png|jpeg)|audio\/(?:mpeg|wav));base64,(.+)$/);if(!m)return send(res,400,{error:"Chỉ hỗ trợ PDF, PNG, JPEG, MP3, WAV dạng base64"});const buf=Buffer.from(m[2],"base64");if(buf.length>5e6)return send(res,413,{error:"File tối đa 5MB"});fs.mkdirSync(UPLOAD_DIR,{recursive:true});const ext=({ "application/pdf":"pdf","image/png":"png","image/jpeg":"jpg","audio/mpeg":"mp3","audio/wav":"wav"})[m[1]],name=id()+"."+ext;fs.writeFileSync(path.join(UPLOAD_DIR,name),buf);const db=load(),mat={id:id(),title:String(d.title||name),url:"/uploads/"+name,type:m[1],ownerId:u.id,createdAt:new Date().toISOString()};db.materials.push(mat);audit(db,u,"material_uploaded",{materialId:mat.id});save(db);return send(res,201,{material:mat})}

 if(req.method==="GET"&&p==="/api/search"){const q=normalize(new URL(req.url,"http://x").searchParams.get("q")||"");const db=load();const data=(()=>{try{const raw=fs.readFileSync(path.join(ROOT,"js","data.js"),"utf8");return raw}catch{return ""}})();const mats=db.materials.filter(m=>normalize(m.title).includes(q)).slice(0,20);return send(res,200,{query:q,materials:mats,hint:data&&q?"Tìm kiếm nội dung học tập phía client hỗ trợ không dấu và autocomplete.":""})}

 if(req.method==="POST"&&p==="/api/ai"){const u=await requireUser(req,res);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const prompt=String(d.prompt||"").slice(0,4000);if(!prompt)return send(res,400,{error:"Thiếu câu hỏi"});if(process.env.AI_API_URL&&process.env.AI_API_KEY){try{const payload={model:process.env.AI_MODEL||"gpt-4.1-mini",messages:[{role:"system",content:"Bạn là giáo viên Toán tiểu học Việt Nam, ưu tiên lớp 4 và lớp 5. Giải thích từng bước thật ngắn, rõ, dùng phép tính kiểm tra lại. Với phép nhân/chia: nêu cách đặt tính và kiểm tra bằng phép ngược. Với phân số: tìm BCNN, quy đồng bằng cách nhân cả tử và mẫu, rồi rút gọn. Với hình học: nêu công thức, thay số, ghi đơn vị cm, cm² hoặc cm³. Không chỉ nêu đáp án; phải chỉ ra vì sao."},{role:"user",content:prompt}]};const r=await fetch(process.env.AI_API_URL,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+process.env.AI_API_KEY},body:JSON.stringify(payload)});const j=await r.json();return send(res,r.ok?200:502,{answer:j.choices?.[0]?.message?.content||j.output_text||"AI chưa trả lời được",provider:true})}catch{return send(res,502,{error:"Không kết nối được AI provider"})}}return send(res,200,{answer:"AI provider chưa được cấu hình. Hãy đặt AI_API_URL, AI_API_KEY và AI_MODEL trong môi trường.",provider:false})}

 if(req.method==="GET"&&p==="/api/admin/stats"){const u=await requireUser(req,res,["admin"]);if(!u)return;const db=load();return send(res,200,{users:db.users.length,students:db.users.filter(x=>x.role==="student").length,teachers:db.users.filter(x=>x.role==="teacher").length,classes:db.classes.length,assignments:db.assignments.length,submissions:db.submissions.length,materials:db.materials.length,audit:db.audit.slice(0,30)})}
 if(req.method==="POST"&&p==="/api/feedback"){const u=await auth(req);let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load();db.feedback.unshift({id:id(),userId:u?.id||null,message:String(d.message||"").slice(0,1000),createdAt:new Date().toISOString()});save(db);return send(res,201,{ok:true})}


 if(req.method==="POST"&&p==="/api/2fa/setup"){const u=await requireUser(req,res,["admin"]);if(!u)return;const db=load(),x=db.users.find(v=>v.id===u.id),secret=newTotpSecret();x.pendingTotpSecret=secret;save(db);const label=encodeURIComponent("BaiTapCap1:"+u.email),issuer=encodeURIComponent("Bai Tap Cap 1");return send(res,200,{secret,otpauth:"otpauth://totp/"+label+"?secret="+secret+"&issuer="+issuer+"&digits=6&period=30"})}
 if(req.method==="POST"&&p==="/api/2fa/enable"){const u=await requireUser(req,res,["admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),x=db.users.find(v=>v.id===u.id);if(!x.pendingTotpSecret||!verifyTotp(x.pendingTotpSecret,d.code))return send(res,400,{error:"Mã 2FA không đúng"});x.totpSecret=x.pendingTotpSecret;delete x.pendingTotpSecret;audit(db,u,"2fa_enabled");save(db);return send(res,200,{ok:true})}
 if(req.method==="GET"&&p==="/api/submissions"){const u=await requireUser(req,res,["teacher","admin"]);if(!u)return;const db=load();let list=db.submissions;if(u.role==="teacher"){const ids=db.assignments.filter(a=>a.teacherId===u.id).map(a=>a.id);list=list.filter(x=>ids.includes(x.assignmentId))}list=list.map(x=>({...x,student:safeUser(db.users.find(v=>v.id===x.studentId)),assignment:db.assignments.find(a=>a.id===x.assignmentId)}));const pg=pageList(list,req,{searchFn:x=>(x.student?.name||"")+" "+(x.student?.email||"")+" "+(x.assignment?.title||"")});return send(res,200,{submissions:pg.items,pagination:pg.pagination})}
 if(req.method==="POST"&&p==="/api/parent/link"){const u=await requireUser(req,res,["parent","admin"]);if(!u)return;if(u.role!=="admin")return send(res,403,{error:"Liên kết phụ huynh cần quản trị viên xác minh trực tiếp. Tính năng tự liên kết tạm khóa."});let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),child=db.users.find(x=>x.role==="student"&&x.email===String(d.studentEmail||"").trim().toLowerCase());if(!child)return send(res,404,{error:"Không tìm thấy học sinh"});const puser=db.users.find(x=>x.id===u.id);puser.children=[...new Set([...(puser.children||[]),child.id])];audit(db,u,"parent_child_linked",{childId:child.id});save(db);return send(res,200,{child:safeUser(child),children:puser.children})}
 if(req.method==="GET"&&p==="/api/integrations"){return send(res,200,{google:!!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET),ai:!!(process.env.AI_API_URL&&process.env.AI_API_KEY),premium:!!process.env.PAYMENT_CHECKOUT_URL,email:!!process.env.SMTP_URL})}
 if(req.method==="GET"&&p==="/api/google/auth"){if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)return send(res,503,{error:"Google OAuth chưa được cấu hình"});const base=process.env.PUBLIC_BASE_URL||("http://localhost:"+PORT),redirect=base.replace(/\/$/,"")+"/api/google/callback",st=crypto.randomBytes(24).toString("hex");oauthStates.set(st,{exp:Date.now()+10*60e3});const q=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:redirect,response_type:"code",scope:"openid email profile",state:st,include_granted_scopes:"true",access_type:"online"});res.writeHead(302,{Location:"https://accounts.google.com/o/oauth2/v2/auth?"+q.toString()});return res.end()}
 if(req.method==="GET"&&p==="/api/google/callback"){const q=new URL(req.url,"http://local").searchParams,st=q.get("state"),code=q.get("code"),saved=oauthStates.get(st);if(!saved||saved.exp<Date.now()||!code)return send(res,400,{error:"Google OAuth state/code không hợp lệ"});oauthStates.delete(st);try{const base=process.env.PUBLIC_BASE_URL||("http://localhost:"+PORT),redirect=base.replace(/\/$/,"")+"/api/google/callback";const tr=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,code,grant_type:"authorization_code",redirect_uri:redirect})});const tj=await tr.json();if(!tr.ok||!tj.access_token)return send(res,502,{error:"Không đổi được Google authorization code"});const ur=await fetch("https://www.googleapis.com/oauth2/v2/userinfo",{headers:{Authorization:"Bearer "+tj.access_token}}),g=await ur.json();if(!ur.ok||!g.email||g.verified_email!==true)return send(res,403,{error:"Email Google chưa được xác minh"});const db=load();let u=db.users.find(x=>x.email===String(g.email).toLowerCase());if(!u){u={id:id(),name:g.name||g.email,email:String(g.email).toLowerCase(),password:hashPassword(crypto.randomBytes(32).toString("hex")),role:"student",grade:1,avatar:g.picture||"👧🏻",emailVerified:true,googleId:g.id,createdAt:new Date().toISOString()};db.users.push(u)}else{if(u.googleId&&u.googleId!==g.id)return send(res,403,{error:"Tài khoản Google không khớp"});if(!u.googleId)return send(res,409,{error:"Email đã tồn tại. Hãy đăng nhập bằng phương thức hiện có trước khi liên kết Google."});u.googleId=g.id;u.emailVerified=true;if(g.picture)u.avatar=g.picture}const t=crypto.randomBytes(32).toString("hex");await sessionStore.set(t,{uid:u.id,exp:Date.now()+TOKEN_TTL},TOKEN_TTL);audit(db,u,"google_login");save(db);res.writeHead(302,{Location:"/?auth_token="+encodeURIComponent(t)+"#home"});return res.end()}catch{return send(res,502,{error:"Google OAuth thất bại"})}}
 if(req.method==="POST"&&p==="/api/premium/checkout"){const u=await requireUser(req,res);if(!u)return;if(!process.env.PAYMENT_CHECKOUT_URL)return send(res,503,{error:"Cổng thanh toán chưa được cấu hình"});const checkout=new URL(process.env.PAYMENT_CHECKOUT_URL);checkout.searchParams.set("user_id",u.id);checkout.searchParams.set("email",u.email);return send(res,200,{checkoutUrl:checkout.toString()})}

 if(req.method==="GET"&&p==="/api/question-bank"){const u=await requireUser(req,res,["teacher","admin"]);if(!u)return;const db=load(),q=new URL(req.url,"http://x").searchParams;let list=db.questionBank;if(q.get("grade"))list=list.filter(x=>String(x.grade)===q.get("grade"));if(q.get("lessonId"))list=list.filter(x=>x.lessonId===q.get("lessonId"));const pg=pageList(list,req,{searchFn:x=>(x.q||x.question||"")+" "+(x.lessonId||"")+" "+(x.level||"")});return send(res,200,{questions:pg.items,pagination:pg.pagination})}
 if(req.method==="POST"&&p==="/api/questions/import-excel"){const u=await requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const m=String(d.dataUrl||"").match(/^data:.*?;base64,(.+)$/);if(!m)return send(res,400,{error:"Thiếu file Excel/CSV dạng dataUrl"});try{const XLSX=require("xlsx"),wb=XLSX.read(Buffer.from(m[1],"base64"),{type:"buffer"}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:""});const db=load(),added=[];for(const row of rows){const opts=[row.A||row.a,row.B||row.b,row.C||row.c,row.D||row.d].map(String);const raw=String(row.answer||row.Answer||row["Đáp án"]||"A").trim().toUpperCase(),ans=/^[ABCD]$/.test(raw)?raw.charCodeAt(0)-65:Math.max(0,Math.min(3,Number(raw)||0));if(!row.q&&!row.question&&!row["Câu hỏi"])continue;const item={id:id(),subject:String(row.subject||"math"),grade:Number(row.grade||row["Lớp"])||4,lessonId:String(row.lessonId||row.lesson||""),level:String(row.level||row["Mức độ"]||"Trung bình"),q:String(row.q||row.question||row["Câu hỏi"]),options:opts,answer:ans,explain:String(row.explain||row["Giải thích"]||"")};db.questionBank.push(item);added.push(item)}audit(db,u,"questions_imported",{count:added.length});save(db);return send(res,201,{count:added.length,questions:added.slice(0,10)})}catch(e){return send(res,400,{error:"Không đọc được file Excel/CSV: "+e.message})}}
 if(req.method==="GET"&&p==="/api/export/results.xlsx"){const u=await requireUser(req,res);if(!u)return;const db=load();let rows=db.results;if(u.role==="student")rows=rows.filter(x=>x.userId===u.id);if(u.role==="parent")rows=rows.filter(x=>u.children?.includes(x.userId));if(u.role==="teacher"){const studentIds=new Set(db.classes.filter(c=>c.teacherId===u.id).flatMap(c=>c.studentIds||[]));rows=rows.filter(x=>studentIds.has(x.userId))}const XLSX=require("xlsx"),data=rows.map(r=>({HocSinh:db.users.find(x=>x.id===r.userId)?.name||r.userId,Bai:r.title,Mon:subjectName(r.subject),Lop:r.grade,Diem:r.score,SoCauDung:r.correct,TongCau:r.total,ThoiGianGiay:r.durationSec,Ngay:r.createdAt})),wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(data);XLSX.utils.book_append_sheet(wb,ws,"Ket qua");const buf=XLSX.write(wb,{type:"buffer",bookType:"xlsx"});res.writeHead(200,{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":'attachment; filename="ket-qua-hoc-tap.xlsx"',"Content-Length":buf.length});return res.end(buf)}
 if(req.method==="GET"&&p==="/api/export/results.pdf"){const u=await requireUser(req,res);if(!u)return;const db=load();let rows=db.results;if(u.role==="student")rows=rows.filter(x=>x.userId===u.id);if(u.role==="parent")rows=rows.filter(x=>u.children?.includes(x.userId));const PDFDocument=require("pdfkit"),doc=new PDFDocument({margin:40});res.writeHead(200,{"Content-Type":"application/pdf","Content-Disposition":'attachment; filename="ket-qua-hoc-tap.pdf"'});doc.pipe(res);doc.fontSize(18).text("BAO CAO KET QUA HOC TAP",{align:"center"}).moveDown();rows.slice(0,200).forEach((r,i)=>doc.fontSize(10).text(`${i+1}. ${r.title} | Lop ${r.grade} | ${r.score}% | ${r.correct}/${r.total}`));doc.end();return}
 if(req.method==="GET"&&p==="/api/exam-rooms"){const u=await requireUser(req,res);if(!u)return;const db=load();let list=db.examRooms;if(u.role==="teacher")list=list.filter(x=>x.teacherId===u.id);if(u.role==="student")list=list.filter(x=>x.participants?.includes(u.id));return send(res,200,{rooms:list})}
 if(req.method==="POST"&&p==="/api/exam-rooms"){const u=await requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),room={id:id(),code:crypto.randomBytes(3).toString("hex").toUpperCase(),title:String(d.title||"Phòng thi Toán"),teacherId:u.id,grade:Number(d.grade)||4,lessonId:String(d.lessonId||"g4-mul"),durationMin:Math.max(5,Number(d.durationMin)||45),startsAt:d.startsAt||null,endsAt:d.endsAt||null,participants:[],createdAt:new Date().toISOString()};db.examRooms.push(room);audit(db,u,"exam_room_created",{roomId:room.id});save(db);return send(res,201,{room})}
 if(req.method==="POST"&&p==="/api/exam-rooms/join"){const u=await requireUser(req,res,["student"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),room=db.examRooms.find(x=>x.code===String(d.code||"").trim().toUpperCase());if(!room)return send(res,404,{error:"Không tìm thấy phòng thi"});const now=Date.now();if(room.startsAt&&now<new Date(room.startsAt).getTime())return send(res,403,{error:"Phòng thi chưa mở"});if(room.endsAt&&now>new Date(room.endsAt).getTime())return send(res,403,{error:"Phòng thi đã đóng"});room.participants=[...new Set([...(room.participants||[]),u.id])];save(db);return send(res,200,{room})}
 if(req.method==="POST"&&p==="/api/ai/analyze-wrong"){const u=await requireUser(req,res);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const items=Array.isArray(d.items)?d.items.slice(0,30):[];const topics={};for(const x of items){const k=x.topic||"Khác";topics[k]=(topics[k]||0)+1}const sorted=Object.entries(topics).sort((a,b)=>b[1]-a[1]),weak=sorted[0]?.[0]||"Chưa xác định";const fallback={weakTopic:weak,summary:items.length?`Em sai ${items.length} câu. Chủ đề cần ôn nhiều nhất: ${weak}.`:"Chưa có câu sai để phân tích.",plan:["Đọc lại quy tắc/công thức","Làm lại câu sai không xem đáp án","Làm 5 câu tương tự","Kiểm tra lại bằng phép tính ngược hoặc công thức"]};if(process.env.AI_API_URL&&process.env.AI_API_KEY&&items.length){try{const prompt="Phân tích lỗi sai Toán lớp "+(d.grade||"4-5")+" cho học sinh tiểu học. Trả lời ngắn, dễ hiểu, giải thích từng bước. Các câu sai: "+JSON.stringify(items);const rr=await fetch(process.env.AI_API_URL,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+process.env.AI_API_KEY},body:JSON.stringify({model:process.env.AI_MODEL||"gpt-4.1-mini",messages:[{role:"system",content:"Bạn là giáo viên Toán tiểu học lớp 4-5, tập trung phép nhân, chia, quy đồng phân số và hình học."},{role:"user",content:prompt}]})});const jj=await rr.json();if(rr.ok)return send(res,200,{...fallback,ai:jj.choices?.[0]?.message?.content||jj.output_text||fallback.summary})}catch{}}return send(res,200,fallback)}
 if(req.method==="GET"&&p==="/api/push/public-key"){if(!process.env.VAPID_PUBLIC_KEY)return send(res,503,{error:"Web Push chưa cấu hình"});return send(res,200,{publicKey:process.env.VAPID_PUBLIC_KEY})}
 if(req.method==="POST"&&p==="/api/push/subscribe"){const u=await requireUser(req,res);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}if(!d.subscription)return send(res,400,{error:"Thiếu subscription"});const db=load();db.pushSubscriptions=db.pushSubscriptions.filter(x=>x.userId!==u.id||x.subscription?.endpoint!==d.subscription.endpoint);db.pushSubscriptions.push({id:id(),userId:u.id,subscription:d.subscription,createdAt:new Date().toISOString()});save(db);return send(res,201,{ok:true})}
 if(req.method==="POST"&&p==="/api/push/send"){const u=await requireUser(req,res,["teacher","admin"]);if(!u)return;if(!process.env.VAPID_PUBLIC_KEY||!process.env.VAPID_PRIVATE_KEY)return send(res,503,{error:"Web Push chưa cấu hình"});let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const webpush=require("web-push");webpush.setVapidDetails(process.env.VAPID_SUBJECT||"mailto:admin@example.com",process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);const db=load(),targets=db.pushSubscriptions.filter(x=>!d.userId||x.userId===d.userId),payload=JSON.stringify({title:String(d.title||"Bài Tập Cấp 1"),body:String(d.body||"Bạn có thông báo mới"),url:d.url||"/#notifications"});const settled=await Promise.allSettled(targets.map(x=>webpush.sendNotification(x.subscription,payload)));return send(res,200,{sent:settled.filter(x=>x.status==="fulfilled").length,failed:settled.filter(x=>x.status==="rejected").length})}
 if(req.method==="GET"&&p==="/api/admin/users"){const u=await requireUser(req,res,["admin"]);if(!u)return;const db=load(),list=db.users.map(safeUser).map(x=>({...x,locked:!!db.users.find(v=>v.id===x.id)?.locked})),pg=pageList(list,req,{searchFn:x=>(x.name||"")+" "+(x.email||"")+" "+(x.role||"")});return send(res,200,{users:pg.items,pagination:pg.pagination})}
 const userPatch=routeMatch(p,"/api/admin/users/:id");if(req.method==="PATCH"&&userPatch){const u=await requireUser(req,res,["admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),x=db.users.find(v=>v.id===userPatch.id);if(!x)return send(res,404,{error:"Không tìm thấy user"});if(["student","parent","teacher","admin"].includes(d.role))x.role=d.role;if(typeof d.locked==="boolean")x.locked=d.locked;if(Number(d.grade)>=1&&Number(d.grade)<=5)x.grade=Number(d.grade);audit(db,u,"user_updated",{target:x.id,role:x.role,locked:!!x.locked});save(db);return send(res,200,{user:safeUser(x),locked:!!x.locked})}
 if(req.method==="GET"&&p==="/api/storage/health"){const u=await requireUser(req,res,["admin"]);if(!u)return;const [pg,redis]=await Promise.all([pgStore.health().catch(e=>({enabled:!!process.env.DATABASE_URL,error:e.message})),sessionStore.health().catch(e=>({enabled:!!process.env.REDIS_URL,error:e.message}))]);return send(res,200,{postgres:pg,redis,storage:storage.status()})}
 if(req.method==="POST"&&p==="/api/storage/migrate"){const u=await requireUser(req,res,["admin"]);if(!u)return;try{return send(res,200,{postgres:await pgStore.migrate()})}catch(e){return send(res,500,{error:e.message})}}
 return send(res,404,{error:"API không tồn tại"});
}

function safeMonitorError(event,meta){try{if(typeof monitor.error==="function")monitor.error(event,meta);else console.error("[monitor]",event,meta)}catch(e){console.error("[monitor-fallback]",event,meta,e.message)}}
let bootPromise=null;
function bootstrap(){
 if(!bootPromise)bootPromise=storage.init().then(()=>{errorTracking.init();seedAdmin();monitor.info("startup",{storage:storage.status(),supabase:supabase.enabled()});return true});
 return bootPromise
}
async function handler(req,res){
 try{
  const parsed=url.parse(req.url,true);
  let p=parsed.pathname;
  const routeParam=typeof parsed.query?.route==="string"?parsed.query.route:"";
  if((p==="/api/index.js"||p==="/api/index")&&routeParam&&/^[a-zA-Z0-9_./-]{1,200}$/.test(routeParam)&&!routeParam.split("/").includes(".."))p="/api/"+routeParam.split("/").filter(Boolean).join("/");
  if(p==="/api/ai-status.js"||p==="/api/ai-status")p="/api/ai/status";
  if(p==="/api/ai-chat.js"||p==="/api/ai-chat")p="/api/ai";
  const ip=req.socket?.remoteAddress||req.headers?.["x-forwarded-for"]||"unknown";
  if(p==="/api/ai/status"&&req.method==="GET"){
   const configured=!!(process.env.AI_API_URL&&process.env.AI_API_KEY);
   let endpointValid=false;
   try{const x=new URL(process.env.AI_API_URL||"");endpointValid=x.protocol==="https:"&&x.pathname.endsWith("/chat/completions")}catch{}
   return send(res,200,{configured,endpointValid,modelConfigured:!!process.env.AI_MODEL,authRequired:true,provider:"openai-compatible",databaseCheck:"not_performed",message:!configured?"Thiếu cấu hình AI_API_URL hoặc AI_API_KEY":!endpointValid?"AI_API_URL cần trỏ đến endpoint HTTPS /chat/completions":"Đã nhận cấu hình AI. Chưa xác minh khóa hoặc quyền truy cập API."});
  }
  if(p.startsWith("/api/")){
   try{await bootstrap()}catch(e){safeMonitorError("database_startup_failed",{message:e.message});return send(res,503,{error:"Cơ sở dữ liệu chưa sẵn sàng. Kiểm tra DATABASE_URL và migrations."})}
   return await api(req,res,p,ip)
  }
  return await staticServer.serve(req,res,STATIC_ROOT,p)
 }catch(e){
  safeMonitorError("request_failed",{message:e.message,url:req.url});errorTracking.capture(e,{url:req.url});
  if(!res.headersSent)send(res,500,{error:"Lỗi máy chủ"});else try{res.end()}catch{}
 }
}
if(require.main===module){
 bootstrap().then(()=>http.createServer((req,res)=>handler(req,res)).listen(PORT,()=>console.log("Bài Tập Cấp 1 running at http://localhost:"+PORT))).catch(e=>{safeMonitorError("startup_failed",{message:e.message});errorTracking.capture(e,{phase:"startup"});console.error("[startup]",e);process.exit(1)})
}
module.exports=handler;
module.exports.handler=handler;
module.exports.bootstrap=bootstrap;
