const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto"),url=require("url");
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,DB_PATH=path.join(ROOT,"data","db.json"),UPLOAD_DIR=path.join(ROOT,"uploads");
const TOKEN_TTL=7*864e5,RESET_TTL=30*60e3,MAX_BODY=2e6;
const sessions=new Map(),rateBuckets=new Map(),resetTokens=new Map(),oauthStates=new Map();

function defaultDb(){return {users:[],classes:[],assignments:[],submissions:[],results:[],notifications:[],materials:[],audit:[],subscriptions:[],feedback:[]}}
function load(){try{return Object.assign(defaultDb(),JSON.parse(fs.readFileSync(DB_PATH,"utf8")))}catch{return defaultDb()}}
function save(db){fs.mkdirSync(path.dirname(DB_PATH),{recursive:true});fs.writeFileSync(DB_PATH,JSON.stringify(db,null,2))}
function id(){return crypto.randomUUID()}
function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){return salt+":"+crypto.scryptSync(password,salt,64).toString("hex")}
function verifyPassword(password,stored=""){try{const [salt,hex]=stored.split(":");const a=Buffer.from(hex,"hex"),b=crypto.scryptSync(password,salt,64);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
function safeUser(u){if(!u)return null;return {id:u.id,name:u.name,email:u.email,role:u.role,grade:u.grade||null,avatar:u.avatar||"👧🏻",emailVerified:!!u.emailVerified,createdAt:u.createdAt}}
function send(res,code,obj,extra={}){res.writeHead(code,{"Content-Type":"application/json; charset=utf-8","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"strict-origin-when-cross-origin","Permissions-Policy":"camera=(), geolocation=(), microphone=(self)",...extra});res.end(JSON.stringify(obj))}
function parseBody(req){return new Promise((resolve,reject)=>{let d="";req.on("data",c=>{d+=c;if(d.length>MAX_BODY){reject(new Error("too_large"));req.destroy()}});req.on("end",()=>{try{resolve(JSON.parse(d||"{}"))}catch{reject(new Error("bad_json"))}})})}
function token(req){return (req.headers.authorization||"").replace(/^Bearer\s+/i,"")}
function auth(req){const t=token(req),s=sessions.get(t);if(!s||s.exp<Date.now()){if(t)sessions.delete(t);return null}const u=load().users.find(x=>x.id===s.uid);return u||null}
function requireUser(req,res,roles){const u=auth(req);if(!u){send(res,401,{error:"Bạn cần đăng nhập"});return null}if(roles&&!roles.includes(u.role)){send(res,403,{error:"Bạn không có quyền thực hiện"});return null}return u}
function rate(ip,key="global",limit=80,windowMs=60e3){const k=ip+":"+key,now=Date.now(),arr=(rateBuckets.get(k)||[]).filter(t=>now-t<windowMs);arr.push(now);rateBuckets.set(k,arr);return arr.length<=limit}
function audit(db,user,action,meta={}){db.audit.unshift({id:id(),userId:user?.id||null,action,meta,at:new Date().toISOString()});db.audit=db.audit.slice(0,1000)}
function subjectName(id){return ({math:"Toán",vietnamese:"Tiếng Việt",english:"Tiếng Anh",nature:"Tự nhiên & Xã hội",science:"Khoa học",history:"Lịch sử & Địa lý"})[id]||id}
function normalize(s=""){return String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function mime(file){return ({".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".svg":"image/svg+xml",".pdf":"application/pdf",".webmanifest":"application/manifest+json"})[path.extname(file).toLowerCase()]||"application/octet-stream"}

function routeMatch(p,pattern){const a=p.split("/").filter(Boolean),b=pattern.split("/").filter(Boolean);if(a.length!==b.length)return null;const params={};for(let i=0;i<b.length;i++){if(b[i].startsWith(":"))params[b[i].slice(1)]=decodeURIComponent(a[i]);else if(a[i]!==b[i])return null}return params}
function seedAdmin(){const db=load();if(!db.users.length&&process.env.SEED_DEMO==="1"){const now=new Date().toISOString();db.users.push(
{id:"demo-student",name:"Bé Minh Anh",email:"hocsinh@demo.vn",password:hashPassword("Demo1234!"),role:"student",grade:3,avatar:"👧🏻",emailVerified:true,createdAt:now},
{id:"demo-teacher",name:"Cô Lan",email:"giaovien@demo.vn",password:hashPassword("Demo1234!"),role:"teacher",avatar:"👩🏻‍🏫",emailVerified:true,createdAt:now},
{id:"demo-parent",name:"Phụ huynh Minh Anh",email:"phuhuynh@demo.vn",password:hashPassword("Demo1234!"),role:"parent",avatar:"👩🏻",emailVerified:true,children:["demo-student"],createdAt:now},
{id:"demo-admin",name:"Quản trị viên",email:"admin@demo.vn",password:hashPassword("Demo1234!"),role:"admin",avatar:"🧑🏻‍💻",emailVerified:true,createdAt:now});save(db)}}
seedAdmin();

async function api(req,res,p,ip){
 if(!rate(ip,"api",120))return send(res,429,{error:"Bạn thao tác quá nhanh"});
 if(req.method==="POST"&&p==="/api/register"){if(!rate(ip,"auth",10,10*60e3))return send(res,429,{error:"Thử lại sau"});let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}
  const email=String(d.email||"").trim().toLowerCase(),password=String(d.password||""),role=["student","parent","teacher"].includes(d.role)?d.role:"student";
  if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return send(res,400,{error:"Email hợp lệ và mật khẩu tối thiểu 8 ký tự"});
  const db=load();if(db.users.some(x=>x.email===email))return send(res,409,{error:"Email đã tồn tại"});
  const u={id:id(),name:String(d.name||"Người dùng").slice(0,80),email,password:hashPassword(password),role,grade:role==="student"?Number(d.grade)||1:null,avatar:role==="teacher"?"👩🏻‍🏫":role==="parent"?"👩🏻":"👧🏻",emailVerified:false,createdAt:new Date().toISOString()};db.users.push(u);audit(db,u,"register");save(db);return send(res,201,{user:safeUser(u),message:"Đăng ký thành công"})}
 if(req.method==="POST"&&p==="/api/login"){if(!rate(ip,"login",8,60e3))return send(res,429,{error:"Quá nhiều lần đăng nhập sai"});let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}
  const db=load(),u=db.users.find(x=>x.email===String(d.email||"").trim().toLowerCase());if(!u||!verifyPassword(String(d.password||""),u.password))return send(res,401,{error:"Sai email hoặc mật khẩu"});
  const t=crypto.randomBytes(32).toString("hex");sessions.set(t,{uid:u.id,exp:Date.now()+TOKEN_TTL});audit(db,u,"login");save(db);return send(res,200,{token:t,user:safeUser(u)})}
 if(req.method==="POST"&&p==="/api/logout"){sessions.delete(token(req));return send(res,200,{ok:true})}
 if(req.method==="GET"&&p==="/api/me"){const u=requireUser(req,res);if(!u)return;return send(res,200,{user:safeUser(u)})}
 if(req.method==="POST"&&p==="/api/forgot-password"){let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),u=db.users.find(x=>x.email===String(d.email||"").trim().toLowerCase());if(u){const t=crypto.randomBytes(24).toString("hex");resetTokens.set(t,{uid:u.id,exp:Date.now()+RESET_TTL});audit(db,u,"password_reset_requested");save(db);if(process.env.NODE_ENV!=="production")return send(res,200,{message:"Đã tạo mã đặt lại mật khẩu (chế độ dev)",resetToken:t})}return send(res,200,{message:"Nếu email tồn tại, hệ thống đã gửi hướng dẫn"})}
 if(req.method==="POST"&&p==="/api/reset-password"){let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const r=resetTokens.get(String(d.token||""));if(!r||r.exp<Date.now())return send(res,400,{error:"Mã đặt lại không hợp lệ hoặc đã hết hạn"});if(String(d.password||"").length<8)return send(res,400,{error:"Mật khẩu tối thiểu 8 ký tự"});const db=load(),u=db.users.find(x=>x.id===r.uid);u.password=hashPassword(String(d.password));resetTokens.delete(String(d.token));audit(db,u,"password_reset");save(db);return send(res,200,{ok:true})}
 if(req.method==="POST"&&p==="/api/verify-email"){const u=requireUser(req,res);if(!u)return;const db=load(),x=db.users.find(v=>v.id===u.id);x.emailVerified=true;audit(db,u,"email_verified");save(db);return send(res,200,{user:safeUser(x)})}

 if(req.method==="GET"&&p==="/api/classes"){const u=requireUser(req,res);if(!u)return;const db=load();const list=u.role==="admin"?db.classes:u.role==="teacher"?db.classes.filter(c=>c.teacherId===u.id):u.role==="student"?db.classes.filter(c=>c.studentIds?.includes(u.id)):db.classes.filter(c=>c.studentIds?.some(s=>u.children?.includes(s)));return send(res,200,{classes:list})}
 if(req.method==="POST"&&p==="/api/classes"){const u=requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),c={id:id(),name:String(d.name||"Lớp học").slice(0,80),grade:Number(d.grade)||1,teacherId:u.id,code:crypto.randomBytes(3).toString("hex").toUpperCase(),studentIds:[],createdAt:new Date().toISOString()};db.classes.push(c);audit(db,u,"class_created",{classId:c.id});save(db);return send(res,201,{class:c})}
 if(req.method==="POST"&&p==="/api/classes/join"){const u=requireUser(req,res,["student"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),c=db.classes.find(x=>x.code===String(d.code||"").trim().toUpperCase());if(!c)return send(res,404,{error:"Không tìm thấy mã lớp"});c.studentIds=[...new Set([...(c.studentIds||[]),u.id])];audit(db,u,"class_joined",{classId:c.id});save(db);return send(res,200,{class:c})}

 if(req.method==="GET"&&p==="/api/assignments"){const u=requireUser(req,res);if(!u)return;const db=load();let list=db.assignments;if(u.role==="teacher")list=list.filter(a=>a.teacherId===u.id);if(u.role==="student"){const classIds=db.classes.filter(c=>c.studentIds?.includes(u.id)).map(c=>c.id);list=list.filter(a=>classIds.includes(a.classId))}return send(res,200,{assignments:list})}
 if(req.method==="POST"&&p==="/api/assignments"){const u=requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),a={id:id(),classId:d.classId,teacherId:u.id,title:String(d.title||"Bài tập"),subject:d.subject||"math",questionIds:Array.isArray(d.questionIds)?d.questionIds:[],deadline:d.deadline||null,maxAttempts:Math.max(1,Number(d.maxAttempts)||1),createdAt:new Date().toISOString()};db.assignments.push(a);audit(db,u,"assignment_created",{assignmentId:a.id});save(db);return send(res,201,{assignment:a})}
 const sub=routeMatch(p,"/api/assignments/:id/submit");if(req.method==="POST"&&sub){const u=requireUser(req,res,["student"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),a=db.assignments.find(x=>x.id===sub.id);if(!a)return send(res,404,{error:"Không tìm thấy bài giao"});const attempts=db.submissions.filter(s=>s.assignmentId===a.id&&s.studentId===u.id).length;if(attempts>=a.maxAttempts)return send(res,409,{error:"Đã hết số lần nộp"});const s={id:id(),assignmentId:a.id,studentId:u.id,answers:d.answers||{},score:Number(d.score)||0,feedback:String(d.feedback||""),submittedAt:new Date().toISOString()};db.submissions.push(s);audit(db,u,"assignment_submitted",{assignmentId:a.id,score:s.score});save(db);return send(res,201,{submission:s})}
 const grade=routeMatch(p,"/api/submissions/:id/grade");if(req.method==="PATCH"&&grade){const u=requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),s=db.submissions.find(x=>x.id===grade.id);if(!s)return send(res,404,{error:"Không tìm thấy bài nộp"});s.score=Math.max(0,Math.min(100,Number(d.score)||0));s.feedback=String(d.feedback||"");s.gradedAt=new Date().toISOString();audit(db,u,"submission_graded",{submissionId:s.id,score:s.score});save(db);return send(res,200,{submission:s})}

 if(req.method==="GET"&&p==="/api/results"){const u=requireUser(req,res);if(!u)return;const db=load();let list=db.results;if(u.role==="student")list=list.filter(r=>r.userId===u.id);if(u.role==="parent")list=list.filter(r=>u.children?.includes(r.userId));return send(res,200,{results:list})}
 if(req.method==="POST"&&p==="/api/results"){const u=requireUser(req,res,["student"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),r={id:id(),userId:u.id,subject:d.subject||"math",grade:Number(d.grade)||u.grade||1,title:String(d.title||"Bài luyện tập"),score:Math.max(0,Math.min(100,Number(d.score)||0)),correct:Number(d.correct)||0,total:Number(d.total)||0,wrongQuestionIds:Array.isArray(d.wrongQuestionIds)?d.wrongQuestionIds:[],durationSec:Number(d.durationSec)||0,createdAt:new Date().toISOString()};db.results.push(r);audit(db,u,"result_saved",{score:r.score});save(db);return send(res,201,{result:r})}

 if(req.method==="GET"&&p==="/api/analytics"){const u=requireUser(req,res);if(!u)return;const db=load();let rs=db.results;if(u.role==="student")rs=rs.filter(r=>r.userId===u.id);if(u.role==="parent")rs=rs.filter(r=>u.children?.includes(r.userId));const bySubject={};for(const r of rs){const k=r.subject||"other";bySubject[k]??={count:0,sum:0,wrong:0};bySubject[k].count++;bySubject[k].sum+=r.score;bySubject[k].wrong+=Math.max(0,(r.total||0)-(r.correct||0))}const subjects=Object.entries(bySubject).map(([id,v])=>({id,name:subjectName(id),attempts:v.count,avg:Math.round(v.sum/v.count),wrong:v.wrong})).sort((a,b)=>a.avg-b.avg);return send(res,200,{totalAttempts:rs.length,average:rs.length?Math.round(rs.reduce((a,b)=>a+b.score,0)/rs.length):0,totalMinutes:Math.round(rs.reduce((a,b)=>a+(b.durationSec||0),0)/60),subjects,weakest:subjects[0]||null})}

 if(req.method==="GET"&&p==="/api/notifications"){const u=requireUser(req,res);if(!u)return;const db=load();return send(res,200,{notifications:db.notifications.filter(n=>!n.userId||n.userId===u.id).slice(0,50)})}
 if(req.method==="POST"&&p==="/api/notifications"){const u=requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),n={id:id(),userId:d.userId||null,title:String(d.title||"Thông báo"),message:String(d.message||""),createdAt:new Date().toISOString()};db.notifications.unshift(n);audit(db,u,"notification_created");save(db);return send(res,201,{notification:n})}

 if(req.method==="POST"&&p==="/api/upload"){const u=requireUser(req,res,["teacher","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const m=String(d.dataUrl||"").match(/^data:(application\/pdf|image\/(?:png|jpeg)|audio\/(?:mpeg|wav));base64,(.+)$/);if(!m)return send(res,400,{error:"Chỉ hỗ trợ PDF, PNG, JPEG, MP3, WAV dạng base64"});const buf=Buffer.from(m[2],"base64");if(buf.length>5e6)return send(res,413,{error:"File tối đa 5MB"});fs.mkdirSync(UPLOAD_DIR,{recursive:true});const ext=({ "application/pdf":"pdf","image/png":"png","image/jpeg":"jpg","audio/mpeg":"mp3","audio/wav":"wav"})[m[1]],name=id()+"."+ext;fs.writeFileSync(path.join(UPLOAD_DIR,name),buf);const db=load(),mat={id:id(),title:String(d.title||name),url:"/uploads/"+name,type:m[1],ownerId:u.id,createdAt:new Date().toISOString()};db.materials.push(mat);audit(db,u,"material_uploaded",{materialId:mat.id});save(db);return send(res,201,{material:mat})}

 if(req.method==="GET"&&p==="/api/search"){const q=normalize(new URL(req.url,"http://x").searchParams.get("q")||"");const db=load();const data=(()=>{try{const raw=fs.readFileSync(path.join(ROOT,"js","data.js"),"utf8");return raw}catch{return ""}})();const mats=db.materials.filter(m=>normalize(m.title).includes(q)).slice(0,20);return send(res,200,{query:q,materials:mats,hint:data&&q?"Tìm kiếm nội dung học tập phía client hỗ trợ không dấu và autocomplete.":""})}

 if(req.method==="POST"&&p==="/api/ai"){const u=requireUser(req,res);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const prompt=String(d.prompt||"").slice(0,4000);if(!prompt)return send(res,400,{error:"Thiếu câu hỏi"});if(process.env.AI_API_URL&&process.env.AI_API_KEY){try{const payload={model:process.env.AI_MODEL||"gpt-4.1-mini",messages:[{role:"system",content:"Bạn là trợ giảng tiểu học. Hướng dẫn từng bước, ngôn ngữ phù hợp lứa tuổi, không đưa đáp án ngay khi có thể gợi mở."},{role:"user",content:prompt}]};const r=await fetch(process.env.AI_API_URL,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+process.env.AI_API_KEY},body:JSON.stringify(payload)});const j=await r.json();return send(res,r.ok?200:502,{answer:j.choices?.[0]?.message?.content||j.output_text||"AI chưa trả lời được",provider:true})}catch{return send(res,502,{error:"Không kết nối được AI provider"})}}return send(res,200,{answer:"AI provider chưa được cấu hình. Hãy đặt AI_API_URL, AI_API_KEY và AI_MODEL trong môi trường.",provider:false})}

 if(req.method==="GET"&&p==="/api/admin/stats"){const u=requireUser(req,res,["admin"]);if(!u)return;const db=load();return send(res,200,{users:db.users.length,students:db.users.filter(x=>x.role==="student").length,teachers:db.users.filter(x=>x.role==="teacher").length,classes:db.classes.length,assignments:db.assignments.length,submissions:db.submissions.length,materials:db.materials.length,audit:db.audit.slice(0,30)})}
 if(req.method==="POST"&&p==="/api/feedback"){const u=auth(req);let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load();db.feedback.unshift({id:id(),userId:u?.id||null,message:String(d.message||"").slice(0,1000),createdAt:new Date().toISOString()});save(db);return send(res,201,{ok:true})}

 if(req.method==="GET"&&p==="/api/submissions"){const u=requireUser(req,res,["teacher","admin"]);if(!u)return;const db=load();let list=db.submissions;if(u.role==="teacher"){const ids=db.assignments.filter(a=>a.teacherId===u.id).map(a=>a.id);list=list.filter(x=>ids.includes(x.assignmentId))}return send(res,200,{submissions:list.map(x=>({...x,student:safeUser(db.users.find(u=>u.id===x.studentId)),assignment:db.assignments.find(a=>a.id===x.assignmentId)}))})}
 if(req.method==="POST"&&p==="/api/parent/link"){const u=requireUser(req,res,["parent","admin"]);if(!u)return;let d;try{d=await parseBody(req)}catch{return send(res,400,{error:"Dữ liệu không hợp lệ"})}const db=load(),child=db.users.find(x=>x.role==="student"&&x.email===String(d.studentEmail||"").trim().toLowerCase());if(!child)return send(res,404,{error:"Không tìm thấy học sinh"});const puser=db.users.find(x=>x.id===u.id);puser.children=[...new Set([...(puser.children||[]),child.id])];audit(db,u,"parent_child_linked",{childId:child.id});save(db);return send(res,200,{child:safeUser(child),children:puser.children})}
 if(req.method==="GET"&&p==="/api/integrations"){return send(res,200,{google:!!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET),ai:!!(process.env.AI_API_URL&&process.env.AI_API_KEY),premium:!!process.env.PAYMENT_CHECKOUT_URL,email:!!process.env.SMTP_URL})}
 if(req.method==="GET"&&p==="/api/google/auth"){if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)return send(res,503,{error:"Google OAuth chưa được cấu hình"});const base=process.env.PUBLIC_BASE_URL||("http://localhost:"+PORT),redirect=base.replace(/\/$/,"")+"/api/google/callback",st=crypto.randomBytes(24).toString("hex");oauthStates.set(st,{exp:Date.now()+10*60e3});const q=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:redirect,response_type:"code",scope:"openid email profile",state:st,include_granted_scopes:"true",access_type:"online"});res.writeHead(302,{Location:"https://accounts.google.com/o/oauth2/v2/auth?"+q.toString()});return res.end()}
 if(req.method==="GET"&&p==="/api/google/callback"){const q=new URL(req.url,"http://local").searchParams,st=q.get("state"),code=q.get("code"),saved=oauthStates.get(st);if(!saved||saved.exp<Date.now()||!code)return send(res,400,{error:"Google OAuth state/code không hợp lệ"});oauthStates.delete(st);try{const base=process.env.PUBLIC_BASE_URL||("http://localhost:"+PORT),redirect=base.replace(/\/$/,"")+"/api/google/callback";const tr=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,code,grant_type:"authorization_code",redirect_uri:redirect})});const tj=await tr.json();if(!tr.ok||!tj.access_token)return send(res,502,{error:"Không đổi được Google authorization code"});const ur=await fetch("https://www.googleapis.com/oauth2/v2/userinfo",{headers:{Authorization:"Bearer "+tj.access_token}}),g=await ur.json();if(!ur.ok||!g.email)return send(res,502,{error:"Không lấy được Google profile"});const db=load();let u=db.users.find(x=>x.email===String(g.email).toLowerCase());if(!u){u={id:id(),name:g.name||g.email,email:String(g.email).toLowerCase(),password:hashPassword(crypto.randomBytes(32).toString("hex")),role:"student",grade:1,avatar:g.picture||"👧🏻",emailVerified:true,googleId:g.id,createdAt:new Date().toISOString()};db.users.push(u)}else{u.googleId=g.id;u.emailVerified=true;if(g.picture)u.avatar=g.picture}const t=crypto.randomBytes(32).toString("hex");sessions.set(t,{uid:u.id,exp:Date.now()+TOKEN_TTL});audit(db,u,"google_login");save(db);res.writeHead(302,{Location:"/?auth_token="+encodeURIComponent(t)+"#home"});return res.end()}catch{return send(res,502,{error:"Google OAuth thất bại"})}}
 if(req.method==="POST"&&p==="/api/premium/checkout"){const u=requireUser(req,res);if(!u)return;if(!process.env.PAYMENT_CHECKOUT_URL)return send(res,503,{error:"Cổng thanh toán chưa được cấu hình"});const checkout=new URL(process.env.PAYMENT_CHECKOUT_URL);checkout.searchParams.set("user_id",u.id);checkout.searchParams.set("email",u.email);return send(res,200,{checkoutUrl:checkout.toString()})}
 return send(res,404,{error:"API không tồn tại"});
}

http.createServer(async(req,res)=>{
 const parsed=url.parse(req.url),p=parsed.pathname,ip=req.socket.remoteAddress||"unknown";
 if(p.startsWith("/api/"))return api(req,res,p,ip);
 let file=p==="/"?"index.html":decodeURIComponent(p.slice(1));file=path.normalize(file).replace(/^(\.\.(\/|\\|$))+/,"");const abs=path.join(ROOT,file);if(!abs.startsWith(ROOT)){res.writeHead(403);return res.end("Forbidden")}
 fs.stat(abs,(err,st)=>{if(err||!st.isFile()){res.writeHead(404);return res.end("Not found")}res.writeHead(200,{"Content-Type":mime(abs),"Cache-Control":file.endsWith(".html")?"no-cache":"public, max-age=3600","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"strict-origin-when-cross-origin","Content-Security-Policy":"default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'self'; img-src 'self' data:; media-src 'self' data:; connect-src 'self' https:; worker-src 'self'; manifest-src 'self'"});fs.createReadStream(abs).pipe(res)})
}).listen(PORT,()=>console.log("Bài Tập Cấp 1 running at http://localhost:"+PORT));
