window.AuthUI=(()=>{
 const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
 let bridge={};
 function setBridge(b){bridge=b||{}}
 function close(){document.querySelector("#modalBackdrop")?.classList.add("hidden")}
 function strength(p){let n=0;if(p.length>=8)n++;if(/[A-Z]/.test(p))n++;if(/[a-z]/.test(p))n++;if(/\d/.test(p))n++;if(/[^A-Za-z0-9]/.test(p))n++;return n}
 async function captcha(form){const cfg=window.SupabaseApp.config?.captcha;if(!cfg?.siteKey)return "";const token=form.querySelector('[name="cf-turnstile-response"]')?.value||"";if(!token)throw new Error("Hãy xác minh CAPTCHA");const r=await API.post("/api/captcha/verify",{token});if(!r.ok)throw new Error("CAPTCHA không hợp lệ");return token}
 function shell(title,subtitle){
  const m=document.querySelector("#modal"),w=document.querySelector("#modalBackdrop");w.classList.remove("hidden");m.className="modal auth-modal";m.innerHTML=`<button class="modal-x" id="authClose">×</button><div class="auth-brand"><div class="auth-logo">🎓</div><div><span>BÀI TẬP CẤP 1</span><h2>${title}</h2><p>${subtitle}</p></div></div><div id="authPane"></div>`;m.querySelector("#authClose").onclick=close;return m.querySelector("#authPane")
 }
 function captchaBox(){const k=window.SupabaseApp.config?.captcha?.siteKey;return k?'<div class="auth-captcha"><div class="turnstile-slot"></div><input type="hidden" name="cf-turnstile-response"></div>':""}
 async function renderCaptcha(root){
  const key=window.SupabaseApp.config?.captcha?.siteKey,slot=root.querySelector(".turnstile-slot");if(!key||!slot)return;
  if(!window.turnstile){
   await new Promise((resolve,reject)=>{const old=document.querySelector("script[data-turnstile-sdk]");if(old){old.addEventListener("load",resolve,{once:true});old.addEventListener("error",reject,{once:true});return}const s=document.createElement("script");s.src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit";s.async=true;s.defer=true;s.dataset.turnstileSdk="1";s.onload=resolve;s.onerror=()=>reject(new Error("Không tải được CAPTCHA"));document.head.appendChild(s)})
  }
  window.turnstile.render(slot,{sitekey:key,theme:"auto",callback:token=>{const i=root.querySelector('[name="cf-turnstile-response"]');if(i)i.value=token},"expired-callback":()=>{const i=root.querySelector('[name="cf-turnstile-response"]');if(i)i.value=""}})
 }
 function open(mode="login"){mode==="register"?register():login();window.SupabaseApp?.ready().catch(e=>console.warn("Auth configuration delayed",e?.message||e))}
 function tabs(active){return `<div class="auth-tabs"><button class="${active==="login"?"active":""}" data-auth-tab="login">Đăng nhập</button><button class="${active==="register"?"active":""}" data-auth-tab="register">Đăng ký</button></div>`}
 function bindTabs(p){p.querySelectorAll("[data-auth-tab]").forEach(b=>b.onclick=()=>b.dataset.authTab==="login"?login():register())}
 function login(){
  const p=shell("Chào mừng quay lại","");p.innerHTML=tabs("login")+`<form id="sbLoginForm" class="auth-form"><label>Email<div class="auth-input"><span>✉️</span><input name="email" type="email" autocomplete="email" placeholder="ten@email.com" required></div></label><label>Mật khẩu<div class="auth-input"><span>🔒</span><input name="password" type="password" autocomplete="current-password" placeholder="••••••••" required><button type="button" class="eye-btn" data-eye>👁</button></div></label>${captchaBox()}<button class="auth-primary">Đăng nhập</button><button type="button" class="google-btn" id="googleLogin"><span>G</span> Tiếp tục với Google</button><button type="button" class="auth-link" id="forgotAuth">Quên mật khẩu?</button><div class="auth-status" id="authStatus"></div></form>`;bindTabs(p);bindEyes(p);renderCaptcha(p).catch(()=>{});
  p.querySelector("#sbLoginForm").onsubmit=async e=>{e.preventDefault();const st=p.querySelector("#authStatus");try{st.textContent="Đang đăng nhập...";const captchaToken=await captcha(e.currentTarget);const d=Object.fromEntries(new FormData(e.currentTarget));if(window.SupabaseApp.enabled()){const {data,error}=await window.SupabaseApp.client.auth.signInWithPassword({email:d.email,password:d.password,...(captchaToken?{options:{captchaToken}}:{})});if(error)throw error;
   if(!data?.session?.access_token)throw new Error("Chưa nhận được phiên đăng nhập.");
   // Supabase has verified the credentials. Show the signed-in shell immediately,
   // with minimum privileges until the server returns the authoritative role.
   const verified=data.user||data.session.user;
   API.setToken(data.session.access_token);
   bridge.setUser?.({id:verified.id,email:verified.email||d.email,name:String(verified.user_metadata?.name||verified.email?.split("@")[0]||"Người dùng"),role:"student",grade:Number(verified.user_metadata?.grade)||4,avatar:"👧🏻",pendingProfile:true});
   close();
   if(location.hash!=="#home")location.hash="#home";
   bridge.toast?.("Đăng nhập thành công");
   window.SupabaseApp.sync(data.session).then(u=>{
    if(!u)throw new Error("Chưa nhận được hồ sơ tài khoản");
    bridge.setUser?.(u);
   }).catch(err=>{console.warn("Profile synchronization failed:",err?.message||err);bridge.toast?.("Không đồng bộ được hồ sơ. Hãy tải lại trang nếu thiếu quyền tài khoản.")});
}else{const j=await API.post("/api/login",d);API.setToken(j.token);bridge.setUser?.(j.user);close();bridge.toast?.("Đăng nhập thành công")}}catch(x){st.textContent=x.message||"Đăng nhập thất bại"}};
  p.querySelector("#googleLogin").onclick=async()=>{try{if(!window.SupabaseApp.enabled())throw new Error("Supabase Auth chưa cấu hình");const redirectTo=window.SupabaseApp.config?.appUrl||location.origin+"/";const {error}=await window.SupabaseApp.client.auth.signInWithOAuth({provider:"google",options:{redirectTo}});if(error)throw error}catch(x){p.querySelector("#authStatus").textContent=x.message}};
  p.querySelector("#forgotAuth").onclick=forgot
 }
 function register(){
  const p=shell("Tạo tài khoản","");p.innerHTML=tabs("register")+`<form id="sbRegisterForm" class="auth-form"><div class="auth-grid"><label>Họ tên<div class="auth-input"><span>👤</span><input name="name" autocomplete="name" required></div></label><label>Vai trò<div class="auth-input"><span>🎒</span><select name="role"><option value="student">Học sinh</option><option value="parent">Phụ huynh</option><option value="teacher">Giáo viên</option></select></div></label></div><label>Email<div class="auth-input"><span>✉️</span><input name="email" type="email" autocomplete="email" required></div></label><div class="auth-grid"><label>Mật khẩu<div class="auth-input"><span>🔒</span><input id="regPassword" name="password" type="password" minlength="8" autocomplete="new-password" required><button type="button" class="eye-btn" data-eye>👁</button></div><div class="password-meter"><span></span><span></span><span></span><span></span><span></span></div></label><label>Lớp<div class="auth-input"><span>📚</span><select name="grade">${[1,2,3,4,5].map(g=>`<option value="${g}" ${g===4?"selected":""}>Lớp ${g}</option>`).join("")}</select></div></label></div>${captchaBox()}<label class="auth-check"><input type="checkbox" required> <span>Tôi đồng ý với Điều khoản và Chính sách riêng tư.</span></label><button class="auth-primary">Tạo tài khoản</button><div class="auth-status" id="authStatus"></div></form>`;bindTabs(p);bindEyes(p);renderCaptcha(p).catch(()=>{});
  const pass=p.querySelector("#regPassword"),meter=p.querySelector(".password-meter");pass.oninput=()=>{const n=strength(pass.value);[...meter.children].forEach((x,i)=>x.classList.toggle("on",i<n))};
  p.querySelector("#sbRegisterForm").onsubmit=async e=>{e.preventDefault();const st=p.querySelector("#authStatus");try{st.textContent="Đang tạo tài khoản...";const captchaToken=await captcha(e.currentTarget);const d=Object.fromEntries(new FormData(e.currentTarget));if(strength(d.password)<3)throw new Error("Mật khẩu cần mạnh hơn");await window.SupabaseApp.ready();if(window.SupabaseApp.enabled()){const redirect=window.SupabaseApp.config?.appUrl||location.origin+"/";const {data,error}=await window.SupabaseApp.client.auth.signUp({email:d.email,password:d.password,options:{emailRedirectTo:redirect,data:{name:d.name,role:d.role,grade:Number(d.grade)},...(captchaToken?{captchaToken}:{})}});if(error)throw error;if(data.session){close();bridge.toast?.("Tạo tài khoản thành công");window.SupabaseApp.sync(data.session).then(u=>{if(u)bridge.setUser?.(u)}).catch(err=>console.warn("Đồng bộ tài khoản chậm:",err?.message||err))}else{st.innerHTML="✅ Yêu cầu đăng ký đã gửi. Nếu hệ thống yêu cầu xác minh, hãy kiểm tra email rồi đăng nhập."}}else{await API.post("/api/register",d);st.textContent="Đăng ký thành công. Hãy đăng nhập.";setTimeout(login,800)}}catch(x){const message=String(x?.message||"");st.textContent=(x?.name==="AbortError"||/abort|hủy bỏ|huỷ bỏ/i.test(message))?"Kết nối đăng ký bị gián đoạn. Hãy kiểm tra tài khoản trong Supabase trước khi thử lại; nếu đã có tài khoản thì chọn Đăng nhập.":message||"Đăng ký thất bại";console.warn("Signup failed",x?.name||"",message)}}
 }
 function forgot(){
  const p=shell("Khôi phục mật khẩu","");p.innerHTML=`<form id="sbForgot" class="auth-form"><label>Email<div class="auth-input"><span>✉️</span><input name="email" type="email" required></div></label><button class="auth-primary">Gửi email đặt lại</button><button type="button" class="auth-link" id="backLogin">← Quay lại đăng nhập</button><div class="auth-status" id="authStatus"></div></form>`;p.querySelector("#backLogin").onclick=login;p.querySelector("#sbForgot").onsubmit=async e=>{e.preventDefault();const st=p.querySelector("#authStatus");try{const email=new FormData(e.currentTarget).get("email");if(window.SupabaseApp.enabled()){const redirectTo=(window.SupabaseApp.config?.appUrl||location.origin+"/")+"#profile";const {error}=await window.SupabaseApp.client.auth.resetPasswordForEmail(email,{redirectTo});if(error)throw error;st.textContent="✅ Đã gửi email đặt lại mật khẩu."}else{const j=await API.post("/api/forgot-password",{email});st.textContent=j.message}}catch(x){st.textContent=x.message}}
 }
 function bindEyes(root){root.querySelectorAll("[data-eye]").forEach(b=>b.onclick=()=>{const i=b.parentElement.querySelector("input");i.type=i.type==="password"?"text":"password"})}
 async function logout(){if(window.SupabaseApp.enabled())await window.SupabaseApp.client.auth.signOut().catch(()=>{});else await API.post("/api/logout",{}).catch(()=>{});API.setToken("");bridge.setUser?.(null)}
 return {open,login,register,forgot,logout,setBridge}
})();