window.AuthUI=(()=>{
 const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
 let bridge={};
 function setBridge(b){bridge=b||{}}
 function close(){document.querySelector("#modalBackdrop")?.classList.add("hidden")}
 function strength(p){let n=0;if(p.length>=8)n++;if(/[A-Z]/.test(p))n++;if(/[a-z]/.test(p))n++;if(/\d/.test(p))n++;if(/[^A-Za-z0-9]/.test(p))n++;return n}
 async function captcha(form){const cfg=window.SupabaseApp.config?.captcha;if(!cfg?.siteKey)return "";const token=form.querySelector('[name="cf-turnstile-response"]')?.value||"";if(!token)throw new Error("Hãy xác minh CAPTCHA");const r=await API.post("/api/captcha/verify",{token});if(!r.ok)throw new Error("CAPTCHA không hợp lệ");return token}
 function shell(title,subtitle){
  const m=document.querySelector("#modal"),w=document.querySelector("#modalBackdrop");w.classList.remove("hidden");m.className="modal auth-modal";m.innerHTML=`<button class="modal-x" id="authClose">×</button><div class="auth-brand"><div class="auth-logo">🎓</div><div><span>BÀI TẬP CẤP 1</span><h2>${title}</h2><p>${subtitle}</p></div></div><div id="authPane"></div>`;m.querySelector("#authClose").onclick=close;return m.querySelector("#authPane")
 }
 function captchaBox(){const k=window.SupabaseApp.config?.captcha?.siteKey;return k?`<div class="auth-captcha"><div class="cf-turnstile" data-sitekey="${esc(k)}" data-theme="auto"></div></div>`:""}
 async function open(mode="login"){await window.SupabaseApp.ready();mode==="register"?register():login()}
 function tabs(active){return `<div class="auth-tabs"><button class="${active==="login"?"active":""}" data-auth-tab="login">Đăng nhập</button><button class="${active==="register"?"active":""}" data-auth-tab="register">Đăng ký</button></div>`}
 function bindTabs(p){p.querySelectorAll("[data-auth-tab]").forEach(b=>b.onclick=()=>b.dataset.authTab==="login"?login():register())}
 function login(){
  const p=shell("Chào mừng quay lại","Đăng nhập để tiếp tục học và đồng bộ tiến độ.");p.innerHTML=tabs("login")+`<form id="sbLoginForm" class="auth-form"><label>Email<div class="auth-input"><span>✉️</span><input name="email" type="email" autocomplete="email" placeholder="ten@email.com" required></div></label><label>Mật khẩu<div class="auth-input"><span>🔒</span><input name="password" type="password" autocomplete="current-password" placeholder="••••••••" required><button type="button" class="eye-btn" data-eye>👁</button></div></label>${captchaBox()}<button class="auth-primary">Đăng nhập</button><button type="button" class="google-btn" id="googleLogin"><span>G</span> Tiếp tục với Google</button><button type="button" class="auth-link" id="forgotAuth">Quên mật khẩu?</button><div class="auth-status" id="authStatus"></div></form>`;bindTabs(p);bindEyes(p);
  p.querySelector("#sbLoginForm").onsubmit=async e=>{e.preventDefault();const st=p.querySelector("#authStatus");try{st.textContent="Đang đăng nhập...";const captchaToken=await captcha(e.currentTarget);const d=Object.fromEntries(new FormData(e.currentTarget));if(window.SupabaseApp.enabled()){const {data,error}=await window.SupabaseApp.client.auth.signInWithPassword({email:d.email,password:d.password,...(captchaToken?{options:{captchaToken}}:{})});if(error)throw error;const u=await window.SupabaseApp.sync(data.session);bridge.setUser?.(u);close();bridge.toast?.("Đăng nhập thành công")}else{const j=await API.post("/api/login",d);API.setToken(j.token);bridge.setUser?.(j.user);close();bridge.toast?.("Đăng nhập thành công")}}catch(x){st.textContent=x.message||"Đăng nhập thất bại"}};
  p.querySelector("#googleLogin").onclick=async()=>{try{if(!window.SupabaseApp.enabled())throw new Error("Supabase Auth chưa cấu hình");const redirectTo=window.SupabaseApp.config?.appUrl||location.origin+"/";const {error}=await window.SupabaseApp.client.auth.signInWithOAuth({provider:"google",options:{redirectTo}});if(error)throw error}catch(x){p.querySelector("#authStatus").textContent=x.message}};
  p.querySelector("#forgotAuth").onclick=forgot
 }
 function register(){
  const p=shell("Tạo tài khoản","Lưu tiến độ an toàn trên Supabase và học trên nhiều thiết bị.");p.innerHTML=tabs("register")+`<form id="sbRegisterForm" class="auth-form"><div class="auth-grid"><label>Họ tên<div class="auth-input"><span>👤</span><input name="name" autocomplete="name" required></div></label><label>Vai trò<div class="auth-input"><span>🎒</span><select name="role"><option value="student">Học sinh</option><option value="parent">Phụ huynh</option><option value="teacher">Giáo viên</option></select></div></label></div><label>Email<div class="auth-input"><span>✉️</span><input name="email" type="email" autocomplete="email" required></div></label><div class="auth-grid"><label>Mật khẩu<div class="auth-input"><span>🔒</span><input id="regPassword" name="password" type="password" minlength="8" autocomplete="new-password" required><button type="button" class="eye-btn" data-eye>👁</button></div><div class="password-meter"><span></span><span></span><span></span><span></span><span></span></div></label><label>Lớp<div class="auth-input"><span>📚</span><select name="grade">${[1,2,3,4,5].map(g=>`<option value="${g}" ${g===4?"selected":""}>Lớp ${g}</option>`).join("")}</select></div></label></div>${captchaBox()}<label class="auth-check"><input type="checkbox" required> <span>Tôi đồng ý với Điều khoản và Chính sách riêng tư.</span></label><button class="auth-primary">Tạo tài khoản</button><div class="auth-status" id="authStatus"></div></form>`;bindTabs(p);bindEyes(p);
  const pass=p.querySelector("#regPassword"),meter=p.querySelector(".password-meter");pass.oninput=()=>{const n=strength(pass.value);[...meter.children].forEach((x,i)=>x.classList.toggle("on",i<n))};
  p.querySelector("#sbRegisterForm").onsubmit=async e=>{e.preventDefault();const st=p.querySelector("#authStatus");try{st.textContent="Đang tạo tài khoản...";const captchaToken=await captcha(e.currentTarget);const d=Object.fromEntries(new FormData(e.currentTarget));if(strength(d.password)<3)throw new Error("Mật khẩu cần mạnh hơn");if(window.SupabaseApp.enabled()){const redirect=window.SupabaseApp.config?.appUrl||location.origin+"/";const {data,error}=await window.SupabaseApp.client.auth.signUp({email:d.email,password:d.password,options:{emailRedirectTo:redirect,data:{name:d.name,role:d.role,grade:Number(d.grade)},...(captchaToken?{captchaToken}:{})}});if(error)throw error;if(data.session){const u=await window.SupabaseApp.sync(data.session);bridge.setUser?.(u);close()}else{st.innerHTML="✅ Tài khoản đã tạo. Hãy mở email để xác minh rồi đăng nhập."}}else{await API.post("/api/register",d);st.textContent="Đăng ký thành công. Hãy đăng nhập.";setTimeout(login,800)}}catch(x){st.textContent=x.message||"Đăng ký thất bại"}}
 }
 function forgot(){
  const p=shell("Khôi phục mật khẩu","Supabase sẽ gửi email đặt lại mật khẩu cho bạn.");p.innerHTML=`<form id="sbForgot" class="auth-form"><label>Email<div class="auth-input"><span>✉️</span><input name="email" type="email" required></div></label><button class="auth-primary">Gửi email đặt lại</button><button type="button" class="auth-link" id="backLogin">← Quay lại đăng nhập</button><div class="auth-status" id="authStatus"></div></form>`;p.querySelector("#backLogin").onclick=login;p.querySelector("#sbForgot").onsubmit=async e=>{e.preventDefault();const st=p.querySelector("#authStatus");try{const email=new FormData(e.currentTarget).get("email");if(window.SupabaseApp.enabled()){const redirectTo=(window.SupabaseApp.config?.appUrl||location.origin+"/")+"#profile";const {error}=await window.SupabaseApp.client.auth.resetPasswordForEmail(email,{redirectTo});if(error)throw error;st.textContent="✅ Đã gửi email đặt lại mật khẩu."}else{const j=await API.post("/api/forgot-password",{email});st.textContent=j.message}}catch(x){st.textContent=x.message}}
 }
 function bindEyes(root){root.querySelectorAll("[data-eye]").forEach(b=>b.onclick=()=>{const i=b.parentElement.querySelector("input");i.type=i.type==="password"?"text":"password"})}
 async function logout(){if(window.SupabaseApp.enabled())await window.SupabaseApp.client.auth.signOut().catch(()=>{});else await API.post("/api/logout",{}).catch(()=>{});API.setToken("");bridge.setUser?.(null)}
 return {open,login,register,forgot,logout,setBridge}
})();